In [1]:
import pandas as pd

# 제주 방언 자모 토큰 구간별 분할

In [2]:
jj_jamo = pd.read_csv("/workspace/datas/jeju/jeju_dialect_jamo_integration.csv", index_col=0)

jj_jamo

,방언,표준어,연령대,출처 파일,길이,셋
0,ㄴ ㅏ ㄴ <SEP> <SPC> ㅈ ㅣ ㄴ <SEP> ㅉ ㅏ <SEP> <SPC> ...,ㄴ ㅏ ㄴ <SEP> <SPC> ㅈ ㅣ ㄴ <SEP> ㅉ ㅏ <SEP> <SPC> ...,50대,DZES20000002.json,6,train
9,ㅇ ㅏ <SEP> <SPC> ㅇ ㅖ <SEP> ㅊ ㅗ <SEP> ㅎ ㅏ <SEP> ...,ㅇ ㅏ <SEP> <SPC> ㅇ ㅖ <SEP> ㅊ ㅗ <SEP> ㅎ ㅏ <SEP> ...,50대,DZES20000002.json,8,train
11,ㅇ ㅏ <SEP> <SPC> ㄱ ㅓ ㅇ <SEP> ㅎ ㅏ <SEP> ㄴ ㅣ <SEP...,ㅇ ㅏ <SEP> <SPC> ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㄴ ㅣ <SEP> ...,50대,DZES20000002.json,6,train
14,ㅈ ㅓ <SEP> ㄱ ㅣ <SEP> <SPC> ㄷ ㅗ ㄹ <SEP> ㅁ ㅔ ㅇ <S...,ㅈ ㅓ <SEP> ㄱ ㅣ <SEP> <SPC> ㄷ ㅗ ㄹ <SEP> ㅁ ㅔ ㅇ <S...,50대,DZES20000002.json,5,train
17,ㄴ ㅏ <SEP> <SPC> ㅇ ㅏ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ㅅ ...,ㄴ ㅏ <SEP> <SPC> ㅇ ㅏ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ㅅ ...,50대,DZES20000002.json,8,train
...,...,...,...,...,...,...
333774,ㅇ ㅏ <SEP> <SPC> ㄴ ㅓ <SEP> <SPC> ㄴ ㅓ <SEP> <SPC...,ㅇ ㅏ <SEP> <SPC> ㄴ ㅓ <SEP> <SPC> ㄴ ㅓ <SEP> <SPC...,30대,DZJD21002409.json,5,test
333778,ㅇ ㅏ <SEP> <SPC> ㅅ ㅣ ㅂ <SEP> ㅇ ㅣ ㄹ <SEP> <SPC> ...,ㅇ ㅏ <SEP> <SPC> ㅅ ㅣ ㅂ <SEP> ㅇ ㅣ ㄹ <SEP> <SPC> ...,30대,DZJD21002409.json,7,test
333782,ㅇ ㅣ ㄹ <SEP> ㅇ ㅛ <SEP> ㅇ ㅣ ㄹ <SEP> <SPC> ㅇ ㅗ <S...,ㅇ ㅣ ㄹ <SEP> ㅇ ㅛ <SEP> ㅇ ㅣ ㄹ <SEP> <SPC> ㅇ ㅗ <S...,30대,DZJD21002409.json,5,test
333790,ㅁ ㅏ ㄱ <SEP> ㄱ ㅓ ㄹ <SEP> ㄹ ㅣ <SEP> ㄴ ㅏ <SEP> <S...,ㅁ ㅏ ㄱ <SEP> ㄱ ㅓ ㄹ <SEP> ㄹ ㅣ <SEP> ㄴ ㅏ <SEP> <S...,30대,DZJD21002409.json,5,test
333800,ㄴ ㅏ ㄴ <SEP> <SPC> ㅊ ㅏ <SEP> <SPC> ㅇ ㅓ <SEP> ㅅ ...,ㄴ ㅏ ㄴ <SEP> <SPC> ㅊ ㅏ <SEP> <SPC> ㅇ ㅓ ㅄ <SEP> ...,30대,DZJD21002409.json,6,test

In [3]:
jj_jamo = jj_jamo.reset_index(drop=True)

In [4]:
seq_len_list = []
for sentence in jj_jamo["방언"].to_list():
    seq_len = len(sentence.split())
    
    seq_len_list.append(seq_len)

jj_jamo.loc[jj_jamo.index, "토큰 길이"] = seq_len_list

jj_jamo

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
0,ㄴ ㅏ ㄴ <SEP> <SPC> ㅈ ㅣ ㄴ <SEP> ㅉ ㅏ <SEP> <SPC> ...,ㄴ ㅏ ㄴ <SEP> <SPC> ㅈ ㅣ ㄴ <SEP> ㅉ ㅏ <SEP> <SPC> ...,50대,DZES20000002.json,6,train,54.0
1,ㅇ ㅏ <SEP> <SPC> ㅇ ㅖ <SEP> ㅊ ㅗ <SEP> ㅎ ㅏ <SEP> ...,ㅇ ㅏ <SEP> <SPC> ㅇ ㅖ <SEP> ㅊ ㅗ <SEP> ㅎ ㅏ <SEP> ...,50대,DZES20000002.json,8,train,70.0
2,ㅇ ㅏ <SEP> <SPC> ㄱ ㅓ ㅇ <SEP> ㅎ ㅏ <SEP> ㄴ ㅣ <SEP...,ㅇ ㅏ <SEP> <SPC> ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㄴ ㅣ <SEP> ...,50대,DZES20000002.json,6,train,54.0
3,ㅈ ㅓ <SEP> ㄱ ㅣ <SEP> <SPC> ㄷ ㅗ ㄹ <SEP> ㅁ ㅔ ㅇ <S...,ㅈ ㅓ <SEP> ㄱ ㅣ <SEP> <SPC> ㄷ ㅗ ㄹ <SEP> ㅁ ㅔ ㅇ <S...,50대,DZES20000002.json,5,train,43.0
4,ㄴ ㅏ <SEP> <SPC> ㅇ ㅏ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ㅅ ...,ㄴ ㅏ <SEP> <SPC> ㅇ ㅏ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ㅅ ...,50대,DZES20000002.json,8,train,74.0
...,...,...,...,...,...,...,...
1535552,ㅇ ㅏ <SEP> <SPC> ㄴ ㅓ <SEP> <SPC> ㄴ ㅓ <SEP> <SPC...,ㅇ ㅏ <SEP> <SPC> ㄴ ㅓ <SEP> <SPC> ㄴ ㅓ <SEP> <SPC...,30대,DZJD21002409.json,5,test,25.0
1535553,ㅇ ㅏ <SEP> <SPC> ㅅ ㅣ ㅂ <SEP> ㅇ ㅣ ㄹ <SEP> <SPC> ...,ㅇ ㅏ <SEP> <SPC> ㅅ ㅣ ㅂ <SEP> ㅇ ㅣ ㄹ <SEP> <SPC> ...,30대,DZJD21002409.json,7,test,47.0
1535554,ㅇ ㅣ ㄹ <SEP> ㅇ ㅛ <SEP> ㅇ ㅣ ㄹ <SEP> <SPC> ㅇ ㅗ <S...,ㅇ ㅣ ㄹ <SEP> ㅇ ㅛ <SEP> ㅇ ㅣ ㄹ <SEP> <SPC> ㅇ ㅗ <S...,30대,DZJD21002409.json,5,test,37.0
1535555,ㅁ ㅏ ㄱ <SEP> ㄱ ㅓ ㄹ <SEP> ㄹ ㅣ <SEP> ㄴ ㅏ <SEP> <S...,ㅁ ㅏ ㄱ <SEP> ㄱ ㅓ ㄹ <SEP> ㄹ ㅣ <SEP> ㄴ ㅏ <SEP> <S...,30대,DZJD21002409.json,5,test,43.0
1535556,ㄴ ㅏ ㄴ <SEP> <SPC> ㅊ ㅏ <SEP> <SPC> ㅇ ㅓ <SEP> ㅅ ...,ㄴ ㅏ ㄴ <SEP> <SPC> ㅊ ㅏ <SEP> <SPC> ㅇ ㅓ ㅄ <SEP> ...,30대,DZJD21002409.json,6,test,39.0

In [12]:
jj_jamo["토큰 길이"].mean()

72.8849720329496

In [5]:
jj_jamo_1 = jj_jamo[jj_jamo["토큰 길이"] <= 106]

jj_jamo_1

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
0,ㄴ ㅏ ㄴ <SEP> <SPC> ㅈ ㅣ ㄴ <SEP> ㅉ ㅏ <SEP> <SPC> ...,ㄴ ㅏ ㄴ <SEP> <SPC> ㅈ ㅣ ㄴ <SEP> ㅉ ㅏ <SEP> <SPC> ...,50대,DZES20000002.json,6,train,54.0
1,ㅇ ㅏ <SEP> <SPC> ㅇ ㅖ <SEP> ㅊ ㅗ <SEP> ㅎ ㅏ <SEP> ...,ㅇ ㅏ <SEP> <SPC> ㅇ ㅖ <SEP> ㅊ ㅗ <SEP> ㅎ ㅏ <SEP> ...,50대,DZES20000002.json,8,train,70.0
2,ㅇ ㅏ <SEP> <SPC> ㄱ ㅓ ㅇ <SEP> ㅎ ㅏ <SEP> ㄴ ㅣ <SEP...,ㅇ ㅏ <SEP> <SPC> ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㄴ ㅣ <SEP> ...,50대,DZES20000002.json,6,train,54.0
3,ㅈ ㅓ <SEP> ㄱ ㅣ <SEP> <SPC> ㄷ ㅗ ㄹ <SEP> ㅁ ㅔ ㅇ <S...,ㅈ ㅓ <SEP> ㄱ ㅣ <SEP> <SPC> ㄷ ㅗ ㄹ <SEP> ㅁ ㅔ ㅇ <S...,50대,DZES20000002.json,5,train,43.0
4,ㄴ ㅏ <SEP> <SPC> ㅇ ㅏ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ㅅ ...,ㄴ ㅏ <SEP> <SPC> ㅇ ㅏ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ㅅ ...,50대,DZES20000002.json,8,train,74.0
...,...,...,...,...,...,...,...
1535552,ㅇ ㅏ <SEP> <SPC> ㄴ ㅓ <SEP> <SPC> ㄴ ㅓ <SEP> <SPC...,ㅇ ㅏ <SEP> <SPC> ㄴ ㅓ <SEP> <SPC> ㄴ ㅓ <SEP> <SPC...,30대,DZJD21002409.json,5,test,25.0
1535553,ㅇ ㅏ <SEP> <SPC> ㅅ ㅣ ㅂ <SEP> ㅇ ㅣ ㄹ <SEP> <SPC> ...,ㅇ ㅏ <SEP> <SPC> ㅅ ㅣ ㅂ <SEP> ㅇ ㅣ ㄹ <SEP> <SPC> ...,30대,DZJD21002409.json,7,test,47.0
1535554,ㅇ ㅣ ㄹ <SEP> ㅇ ㅛ <SEP> ㅇ ㅣ ㄹ <SEP> <SPC> ㅇ ㅗ <S...,ㅇ ㅣ ㄹ <SEP> ㅇ ㅛ <SEP> ㅇ ㅣ ㄹ <SEP> <SPC> ㅇ ㅗ <S...,30대,DZJD21002409.json,5,test,37.0
1535555,ㅁ ㅏ ㄱ <SEP> ㄱ ㅓ ㄹ <SEP> ㄹ ㅣ <SEP> ㄴ ㅏ <SEP> <S...,ㅁ ㅏ ㄱ <SEP> ㄱ ㅓ ㄹ <SEP> ㄹ ㅣ <SEP> ㄴ ㅏ <SEP> <S...,30대,DZJD21002409.json,5,test,43.0
1535556,ㄴ ㅏ ㄴ <SEP> <SPC> ㅊ ㅏ <SEP> <SPC> ㅇ ㅓ <SEP> ㅅ ...,ㄴ ㅏ ㄴ <SEP> <SPC> ㅊ ㅏ <SEP> <SPC> ㅇ ㅓ ㅄ <SEP> ...,30대,DZJD21002409.json,6,test,39.0

In [6]:
jj_jamo_1[jj_jamo_1["셋"] == "train"]

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
0,ㄴ ㅏ ㄴ <SEP> <SPC> ㅈ ㅣ ㄴ <SEP> ㅉ ㅏ <SEP> <SPC> ...,ㄴ ㅏ ㄴ <SEP> <SPC> ㅈ ㅣ ㄴ <SEP> ㅉ ㅏ <SEP> <SPC> ...,50대,DZES20000002.json,6,train,54.0
1,ㅇ ㅏ <SEP> <SPC> ㅇ ㅖ <SEP> ㅊ ㅗ <SEP> ㅎ ㅏ <SEP> ...,ㅇ ㅏ <SEP> <SPC> ㅇ ㅖ <SEP> ㅊ ㅗ <SEP> ㅎ ㅏ <SEP> ...,50대,DZES20000002.json,8,train,70.0
2,ㅇ ㅏ <SEP> <SPC> ㄱ ㅓ ㅇ <SEP> ㅎ ㅏ <SEP> ㄴ ㅣ <SEP...,ㅇ ㅏ <SEP> <SPC> ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㄴ ㅣ <SEP> ...,50대,DZES20000002.json,6,train,54.0
3,ㅈ ㅓ <SEP> ㄱ ㅣ <SEP> <SPC> ㄷ ㅗ ㄹ <SEP> ㅁ ㅔ ㅇ <S...,ㅈ ㅓ <SEP> ㄱ ㅣ <SEP> <SPC> ㄷ ㅗ ㄹ <SEP> ㅁ ㅔ ㅇ <S...,50대,DZES20000002.json,5,train,43.0
4,ㄴ ㅏ <SEP> <SPC> ㅇ ㅏ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ㅅ ...,ㄴ ㅏ <SEP> <SPC> ㅇ ㅏ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ㅅ ...,50대,DZES20000002.json,8,train,74.0
...,...,...,...,...,...,...,...
1375428,ㄷ ㅜ <SEP> <SPC> ㅁ ㅕ ㅇ <SEP> <SPC> ㅇ ㅣ <SEP> <S...,ㄷ ㅜ <SEP> <SPC> ㅁ ㅕ ㅇ <SEP> <SPC> ㅇ ㅣ <SEP> <S...,30대,DZJD21002407.json,10,train,77.0
1375429,ㄴ ㅏ <SEP> <SPC> ㅈ ㅣ ㅂ <SEP> ㅇ ㅔ <SEP> <SPC> ㅎ ...,ㄴ ㅏ <SEP> <SPC> ㅈ ㅣ ㅂ <SEP> ㅇ ㅔ <SEP> <SPC> ㅎ ...,30대,DZJD21002407.json,9,train,103.0
1375431,ㅅ ㅐ ㄱ <SEP> ㄲ ㅏ ㄹ <SEP> <SPC> ㅂ ㅏ ㄴ <SEP> ㅈ ㅓ ...,ㅅ ㅐ ㄱ <SEP> ㄲ ㅏ ㄹ <SEP> <SPC> ㅂ ㅏ ㄴ <SEP> ㅈ ㅓ ...,30대,DZJD21002407.json,6,train,55.0
1375433,n <SEP> a <SEP> m <SEP> e <SEP> ㅇ ㅣ <SEP> <SPC...,n <SEP> a <SEP> m <SEP> e <SEP> ㅇ ㅣ <SEP> <SPC...,30대,DZJD21002407.json,8,train,81.0
1375434,ㅇ ㅓ <SEP> <SPC> ㅁ ㅏ ㅈ <SEP> ㅇ ㅏ <SEP> <SPC> ㄴ ...,ㅇ ㅓ <SEP> <SPC> ㅁ ㅏ ㅈ <SEP> ㅇ ㅏ <SEP> <SPC> ㄴ ...,30대,DZJD21002407.json,5,train,38.0

In [21]:
jj_jamo_1.to_csv("/workspace/datas/jeju/jeju_dialect_jamo_integration_1.csv")

In [7]:
jj_jamo_2 = jj_jamo[(jj_jamo["토큰 길이"] >= 107) & (jj_jamo["토큰 길이"] < 196)]

jj_jamo_2

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
6,ㅇ ㅏ <SEP> ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㄴ ㅣ <SEP> ㄲ ㅏ <S...,ㅇ ㅏ <SEP> ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㄴ ㅣ <SEP> ㄲ ㅏ <S...,50대,DZES20000002.json,11,train,109.0
49,ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㄴ ㅣ <SEP> ㄲ ㅏ <SEP> <SPC> ...,ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㄴ ㅣ <SEP> ㄲ ㅏ <SEP> <SPC> ...,50대,DZES20000002.json,10,train,117.0
51,ㄱ ㅡ <SEP> ㄸ ㅐ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ㄴ ㅗ ㅇ <S...,ㄱ ㅡ <SEP> ㄸ ㅐ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ㄴ ㅗ ㅇ <S...,50대,DZES20000002.json,12,train,131.0
52,ㅇ ㅛ <SEP> ㅈ ㅡ ㅁ <SEP> ㅇ ㅡ ㄴ <SEP> <SPC> ㅇ ㅝ <S...,ㅇ ㅛ <SEP> ㅈ ㅡ ㅁ <SEP> ㅇ ㅡ ㄴ <SEP> <SPC> ㅇ ㅝ <S...,50대,DZES20000002.json,11,train,110.0
62,ㅇ ㅓ <SEP> ㅇ ㅓ <SEP> <SPC> ㅇ ㅓ <SEP> <SPC> ㄱ ㅡ ...,ㅇ ㅓ <SEP> ㅇ ㅓ <SEP> <SPC> ㅇ ㅓ <SEP> <SPC> ㄱ ㅡ ...,50대,DZES20000002.json,11,train,108.0
...,...,...,...,...,...,...,...
1535530,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㄱ ㅏ <SEP> ㅈ ㅣ <SEP> ㄱ ㅜ <S...,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㄱ ㅏ <SEP> ㅈ ㅣ <SEP> ㄱ ㅜ <S...,30대,DZJD21002409.json,15,test,139.0
1535532,ㄱ ㅡ <SEP> <SPC> ㅈ ㅓ <SEP> <SPC> ㄹ ㅓ ㄴ <SEP> ㄴ ...,ㄱ ㅡ <SEP> <SPC> ㅈ ㅓ <SEP> <SPC> ㄹ ㅓ ㄴ <SEP> ㄴ ...,30대,DZJD21002409.json,11,test,115.0
1535543,ㄱ ㅑ ㅇ <SEP> <SPC> ㄱ ㅡ ㅂ <SEP> ㅎ ㅐ <SEP> ㄱ ㅏ <S...,ㄱ ㅑ ㅇ <SEP> <SPC> ㄱ ㅡ ㅂ <SEP> ㅎ ㅐ <SEP> ㄱ ㅏ <S...,30대,DZJD21002409.json,13,test,107.0
1535544,ㅇ ㅣ <SEP> ㅈ ㅔ <SEP> <SPC> ㅈ ㅜ ㅇ <SEP> ㅎ ㅏ ㄱ <S...,ㅇ ㅣ <SEP> ㅈ ㅔ <SEP> <SPC> ㅈ ㅜ ㅇ <SEP> ㅎ ㅏ ㄱ <S...,30대,DZJD21002409.json,13,test,118.0
1535549,ㄴ ㅏ <SEP> <SPC> ㄴ ㅏ <SEP> <SPC> ㅅ ㅣ ㅂ <SEP> ㅅ ...,ㄴ ㅏ <SEP> <SPC> ㄴ ㅏ <SEP> <SPC> ㅅ ㅣ ㅂ <SEP> ㅅ ...,30대,DZJD21002409.json,15,test,121.0

In [8]:
jj_jamo_2[jj_jamo_2["셋"] == "train"]

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
6,ㅇ ㅏ <SEP> ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㄴ ㅣ <SEP> ㄲ ㅏ <S...,ㅇ ㅏ <SEP> ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㄴ ㅣ <SEP> ㄲ ㅏ <S...,50대,DZES20000002.json,11,train,109.0
49,ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㄴ ㅣ <SEP> ㄲ ㅏ <SEP> <SPC> ...,ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㄴ ㅣ <SEP> ㄲ ㅏ <SEP> <SPC> ...,50대,DZES20000002.json,10,train,117.0
51,ㄱ ㅡ <SEP> ㄸ ㅐ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ㄴ ㅗ ㅇ <S...,ㄱ ㅡ <SEP> ㄸ ㅐ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ㄴ ㅗ ㅇ <S...,50대,DZES20000002.json,12,train,131.0
52,ㅇ ㅛ <SEP> ㅈ ㅡ ㅁ <SEP> ㅇ ㅡ ㄴ <SEP> <SPC> ㅇ ㅝ <S...,ㅇ ㅛ <SEP> ㅈ ㅡ ㅁ <SEP> ㅇ ㅡ ㄴ <SEP> <SPC> ㅇ ㅝ <S...,50대,DZES20000002.json,11,train,110.0
62,ㅇ ㅓ <SEP> ㅇ ㅓ <SEP> <SPC> ㅇ ㅓ <SEP> <SPC> ㄱ ㅡ ...,ㅇ ㅓ <SEP> ㅇ ㅓ <SEP> <SPC> ㅇ ㅓ <SEP> <SPC> ㄱ ㅡ ...,50대,DZES20000002.json,11,train,108.0
...,...,...,...,...,...,...,...
1375404,ㅎ ㅣ <SEP> ㅌ ㅡ ㄹ <SEP> ㄹ ㅓ <SEP> <SPC> ㄱ ㅡ <SEP...,ㅎ ㅣ <SEP> ㅌ ㅡ ㄹ <SEP> ㄹ ㅓ <SEP> <SPC> ㄱ ㅡ <SEP...,30대,DZJD21002407.json,16,train,147.0
1375405,ㄱ ㅡ <SEP> <SPC> ㄱ ㅔ <SEP> ㅇ ㅣ ㅁ <SEP> <SPC> ㅇ ...,ㄱ ㅡ <SEP> <SPC> ㄱ ㅔ <SEP> ㅇ ㅣ ㅁ <SEP> <SPC> ㅇ ...,30대,DZJD21002407.json,12,train,113.0
1375427,ㅂ ㅗ <SEP> ㄷ ㅡ <SEP> ㄱ ㅔ <SEP> ㅇ ㅣ ㅁ <SEP> <SPC...,ㅂ ㅗ <SEP> ㄷ ㅡ <SEP> ㄱ ㅔ <SEP> ㅇ ㅣ ㅁ <SEP> <SPC...,30대,DZJD21002407.json,13,train,124.0
1375430,ㅇ ㅓ <SEP> <SPC> ㄹ ㅜ <SEP> ㅁ ㅣ <SEP> ㅋ ㅠ <SEP> ...,ㅇ ㅓ <SEP> <SPC> ㄹ ㅜ <SEP> ㅁ ㅣ <SEP> ㅋ ㅠ <SEP> ...,30대,DZJD21002407.json,16,train,131.0
1375432,ㄱ ㅡ <SEP> ㄹ ㅣ <SEP> ㄱ ㅗ <SEP> <SPC> ㅇ ㅛ <SEP> ...,ㄱ ㅡ <SEP> ㄹ ㅣ <SEP> ㄱ ㅗ <SEP> <SPC> ㅇ ㅛ <SEP> ...,30대,DZJD21002407.json,16,train,164.0

In [25]:
jj_jamo_2.to_csv("/workspace/datas/jeju/jeju_dialect_jamo_integration_2.csv")

In [9]:
jj_jamo_3 = jj_jamo[(jj_jamo["토큰 길이"] >= 196) & (jj_jamo["토큰 길이"] < 285)]

jj_jamo_3

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
2242,ㅇ ㅣ <SEP> ㄹ ㅓ ㄴ <SEP> <SPC> ㄱ ㅓ <SEP> <SPC> ㅂ ...,ㅇ ㅣ <SEP> ㄹ ㅓ ㄴ <SEP> <SPC> ㄱ ㅓ <SEP> <SPC> ㅂ ...,20대,DZES20000023.json,21,train,217.0
2315,ㄱ ㅓ ㅇ <SEP> ㅎ ㅐ <SEP> ㄴ ㅏ ㄴ <SEP> <SPC> ㄱ ㅛ <S...,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㄱ ㅛ <SEP> ...,60대 이상,DZES20000023.json,19,train,201.0
2321,ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㄱ ㅗ <SEP> <SPC> ㄴ ㅏ <SEP> ...,ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㄱ ㅗ <SEP> <SPC> ㄴ ㅏ <SEP> ...,60대 이상,DZES20000023.json,18,train,196.0
2448,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㅇ ㅏ <SEP> ...,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㅇ ㅏ <SEP> ...,20대,DZES20000026.json,23,train,229.0
2457,ㅇ ㅣ ㄹ <SEP> ㅇ ㅣ <SEP> <SPC> ㅂ ㅐ ㄱ <SEP> ㅇ ㅝ ㄴ ...,ㅇ ㅣ ㄹ <SEP> ㅇ ㅣ <SEP> <SPC> ㅂ ㅐ ㄱ <SEP> ㅇ ㅝ ㄴ ...,20대,DZES20000026.json,21,train,211.0
...,...,...,...,...,...,...,...
1529918,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㅇ ㅣ <SEP> ...,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> # <SEP> ㅇ ...,20대,DZJD20001646.json,26,test,218.0
1532608,ㅇ ㅣ <SEP> ㄱ ㅓ <SEP> <SPC> ㅈ ㅣ ㄴ <SEP> ㅉ ㅏ <SEP...,ㅇ ㅣ <SEP> ㄱ ㅓ <SEP> <SPC> ㅈ ㅣ ㄴ <SEP> ㅉ ㅏ <SEP...,30대,DZJD21002366.json,33,test,229.0
1532614,ㅁ ㅏ ㄱ <SEP> <SPC> ㅁ ㅏ <SEP> ㅈ ㅣ <SEP> ㅁ ㅏ ㄱ <S...,ㅁ ㅏ ㄱ <SEP> <SPC> ㅁ ㅏ <SEP> ㅈ ㅣ <SEP> ㅁ ㅏ ㄱ <S...,30대,DZJD21002366.json,24,test,209.0
1532622,ㄱ ㅡ <SEP> <SPC> ㅇ ㅕ <SEP> ㅈ ㅣ ㄱ <SEP> ㅇ ㅝ ㄴ <S...,ㄱ ㅡ <SEP> <SPC> ㅇ ㅕ <SEP> ㅈ ㅣ ㄱ <SEP> ㅇ ㅝ ㄴ <S...,30대,DZJD21002366.json,26,test,248.0
1532654,ㅋ ㅓ <SEP> ㅍ ㅣ <SEP> <SPC> ㅁ ㅏ ㄴ <SEP> ㄷ ㅡ <SEP...,ㅋ ㅓ <SEP> ㅍ ㅣ <SEP> <SPC> ㅁ ㅏ ㄴ <SEP> ㄷ ㅡ <SEP...,30대,DZJD21002366.json,23,test,229.0

In [11]:
jj_jamo_3[jj_jamo_3["셋"] == "train"]

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
2242,ㅇ ㅣ <SEP> ㄹ ㅓ ㄴ <SEP> <SPC> ㄱ ㅓ <SEP> <SPC> ㅂ ...,ㅇ ㅣ <SEP> ㄹ ㅓ ㄴ <SEP> <SPC> ㄱ ㅓ <SEP> <SPC> ㅂ ...,20대,DZES20000023.json,21,train,217.0
2315,ㄱ ㅓ ㅇ <SEP> ㅎ ㅐ <SEP> ㄴ ㅏ ㄴ <SEP> <SPC> ㄱ ㅛ <S...,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㄱ ㅛ <SEP> ...,60대 이상,DZES20000023.json,19,train,201.0
2321,ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㄱ ㅗ <SEP> <SPC> ㄴ ㅏ <SEP> ...,ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㄱ ㅗ <SEP> <SPC> ㄴ ㅏ <SEP> ...,60대 이상,DZES20000023.json,18,train,196.0
2448,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㅇ ㅏ <SEP> ...,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㅇ ㅏ <SEP> ...,20대,DZES20000026.json,23,train,229.0
2457,ㅇ ㅣ ㄹ <SEP> ㅇ ㅣ <SEP> <SPC> ㅂ ㅐ ㄱ <SEP> ㅇ ㅝ ㄴ ...,ㅇ ㅣ ㄹ <SEP> ㅇ ㅣ <SEP> <SPC> ㅂ ㅐ ㄱ <SEP> ㅇ ㅝ ㄴ ...,20대,DZES20000026.json,21,train,211.0
...,...,...,...,...,...,...,...
1372342,ㅂ ㅗ <SEP> ㅌ ㅗ ㅇ <SEP> <SPC> ㄱ ㅡ <SEP> ㄹ ㅐ <SEP...,ㅂ ㅗ <SEP> ㅌ ㅗ ㅇ <SEP> <SPC> ㄱ ㅡ <SEP> ㄹ ㅐ <SEP...,20대,DZJD21002296.json,28,train,232.0
1372387,ㄴ ㅐ <SEP> ㄱ ㅏ <SEP> <SPC> ㄱ ㅜ ㄱ <SEP> ㅈ ㅔ <SEP...,ㄴ ㅐ <SEP> ㄱ ㅏ <SEP> <SPC> ㄱ ㅜ ㄱ <SEP> ㅈ ㅔ <SEP...,20대,DZJD21002296.json,20,train,224.0
1372513,ㅇ ㅏ <SEP> ㄴ ㅣ <SEP> <SPC> ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP...,ㅇ ㅏ <SEP> ㄴ ㅣ <SEP> <SPC> ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP...,20대,DZJD21002296.json,24,train,208.0
1372564,ㅇ ㅏ ㅁ <SEP> ㅌ ㅡ ㄴ <SEP> <SPC> ㄸ ㅏ ㄴ <SEP> <SPC...,ㅇ ㅏ ㅁ <SEP> ㅌ ㅡ ㄴ <SEP> <SPC> ㄸ ㅏ ㄴ <SEP> <SPC...,20대,DZJD21002296.json,25,train,235.0
1372666,ㅇ ㅏ <SEP> ㄴ ㅣ <SEP> <SPC> ㄱ ㅡ <SEP> ㄴ ㅣ <SEP> ...,ㅇ ㅏ <SEP> ㄴ ㅣ <SEP> <SPC> ㄱ ㅡ <SEP> ㄴ ㅣ <SEP> ...,30대,DZJD21002316.json,23,train,207.0

In [27]:
jj_jamo_3.to_csv("/workspace/datas/jeju/jeju_dialect_jamo_integration_3.csv")

In [13]:
jj_jamo_4 = jj_jamo[(jj_jamo["토큰 길이"] >= 285) & (jj_jamo["토큰 길이"] < 374)]

jj_jamo_4

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
27721,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㅁ ㅝ <SEP> ...,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㅁ ㅝ <SEP> ...,20대,DZES20000137.json,34,train,291.0
27796,ㄱ ㅓ <SEP> ㄱ ㅣ <SEP> <SPC> ㄱ ㅏ <SEP> ㄴ ㅣ <SEP> ...,ㄱ ㅓ <SEP> ㄱ ㅣ <SEP> <SPC> ㄱ ㅏ <SEP> ㄴ ㅣ <SEP> ...,20대,DZES20000137.json,31,train,288.0
27797,ㄷ ㅏ <SEP> ㄱ ㅏ <SEP> ㅇ ㅗ <SEP> ㅁ ㅕ ㄴ <SEP> <SPC...,ㄷ ㅏ <SEP> ㄱ ㅏ <SEP> ㅇ ㅗ <SEP> ㅁ ㅕ ㄴ <SEP> <SPC...,20대,DZES20000137.json,26,train,296.0
27812,x <SEP> x <SEP> ㄷ ㅏ <SEP> ㄱ ㅏ <SEP> <SPC> ㅇ ㅣ ...,x <SEP> x <SEP> ㄷ ㅏ <SEP> ㄱ ㅏ <SEP> <SPC> ㅇ ㅣ ...,30대,DZES20000137.json,30,train,305.0
55550,ㄴ ㅐ <SEP> <SPC> ㅅ ㅐ ㅇ <SEP> ㄱ ㅏ ㄱ <SEP> ㅇ ㅡ ㄴ ...,ㄴ ㅐ <SEP> <SPC> ㅅ ㅐ ㅇ <SEP> ㄱ ㅏ ㄱ <SEP> ㅇ ㅡ ㄴ ...,40대,DZES20000269.json,35,train,338.0
...,...,...,...,...,...,...,...
1480484,ㅈ ㅓ ㄴ <SEP> ㅎ ㅘ <SEP> ㄹ ㅗ <SEP> ㄷ ㅗ <SEP> <SPC...,ㅈ ㅓ ㄴ <SEP> ㅎ ㅘ <SEP> ㄹ ㅗ <SEP> ㄷ ㅗ <SEP> <SPC...,20대,DZES21001220.json,30,test,288.0
1486423,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㄴ ㅐ <SEP> ...,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㄴ ㅐ <SEP> ...,20대,DZES21001306.json,31,test,308.0
1525551,ㄴ ㅐ <SEP> ㄱ ㅏ <SEP> <SPC> ㄴ ㅓ <SEP> <SPC> ㄴ ㅓ ...,ㄴ ㅐ <SEP> ㄱ ㅏ <SEP> <SPC> ㄴ ㅓ <SEP> <SPC> ㄴ ㅓ ...,20대,DZJD20001505.json,34,test,307.0
1525553,ㅇ ㅓ <SEP> <SPC> ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㄱ ㅏ <SEP> ...,ㅇ ㅓ <SEP> <SPC> ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㄱ ㅏ <SEP> ...,20대,DZJD20001505.json,29,test,299.0
1525630,ㄱ ㅣ <SEP> ㄴ ㅑ <SEP> <SPC> ㅇ ㅏ <SEP> ㄴ ㅣ <SEP> ...,ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㄴ ㅑ <SEP> <SPC> ㅇ ㅏ <SEP> ...,20대,DZJD20001505.json,32,test,296.0

In [14]:
jj_jamo_4[jj_jamo_4["셋"] == "train"]

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
27721,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㅁ ㅝ <SEP> ...,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㅁ ㅝ <SEP> ...,20대,DZES20000137.json,34,train,291.0
27796,ㄱ ㅓ <SEP> ㄱ ㅣ <SEP> <SPC> ㄱ ㅏ <SEP> ㄴ ㅣ <SEP> ...,ㄱ ㅓ <SEP> ㄱ ㅣ <SEP> <SPC> ㄱ ㅏ <SEP> ㄴ ㅣ <SEP> ...,20대,DZES20000137.json,31,train,288.0
27797,ㄷ ㅏ <SEP> ㄱ ㅏ <SEP> ㅇ ㅗ <SEP> ㅁ ㅕ ㄴ <SEP> <SPC...,ㄷ ㅏ <SEP> ㄱ ㅏ <SEP> ㅇ ㅗ <SEP> ㅁ ㅕ ㄴ <SEP> <SPC...,20대,DZES20000137.json,26,train,296.0
27812,x <SEP> x <SEP> ㄷ ㅏ <SEP> ㄱ ㅏ <SEP> <SPC> ㅇ ㅣ ...,x <SEP> x <SEP> ㄷ ㅏ <SEP> ㄱ ㅏ <SEP> <SPC> ㅇ ㅣ ...,30대,DZES20000137.json,30,train,305.0
55550,ㄴ ㅐ <SEP> <SPC> ㅅ ㅐ ㅇ <SEP> ㄱ ㅏ ㄱ <SEP> ㅇ ㅡ ㄴ ...,ㄴ ㅐ <SEP> <SPC> ㅅ ㅐ ㅇ <SEP> ㄱ ㅏ ㄱ <SEP> ㅇ ㅡ ㄴ ...,40대,DZES20000269.json,35,train,338.0
...,...,...,...,...,...,...,...
1307409,ㅇ ㅏ ㄹ <SEP> ㅇ ㅏ <SEP> ㅂ ㅗ ㄴ <SEP> <SPC> ㄷ ㅏ <S...,ㅇ ㅏ ㄹ <SEP> ㅇ ㅏ <SEP> ㅂ ㅗ ㄴ <SEP> <SPC> ㄷ ㅏ <S...,40대,DZJD21001894.json,29,train,296.0
1323257,ㄱ ㅓ ㅇ <SEP> ㅎ ㅏ <SEP> ㄱ ㅗ <SEP> . <SEP> <SPC> ...,ㄱ ㅡ <SEP> ㄹ ㅣ <SEP> ㄱ ㅗ <SEP> . <SEP> <SPC> ㄸ ...,60대 이상,DZJD21001967.json,25,train,297.0
1323282,ㅇ ㅓ <SEP> ㄹ ㅕ ㄴ <SEP> ㅎ ㅣ <SEP> <SPC> ㅇ ㅘ ㅇ <S...,ㅇ ㅓ <SEP> ㄹ ㅕ ㄴ <SEP> ㅎ ㅣ <SEP> <SPC> ㅇ ㅘ <SEP...,60대 이상,DZJD21001967.json,27,train,311.0
1323301,ㅇ ㅓ <SEP> ㅋ ㅕ <SEP> . <SEP> <SPC> ㅊ ㅜ <SEP> ㅇ ...,ㅇ ㅓ ㄹ <SEP> ㄱ ㅔ ㅆ <SEP> ㄷ ㅏ <SEP> . <SEP> <SPC...,60대 이상,DZJD21001967.json,20,train,290.0
1323373,ㄱ ㅡ <SEP> <SPC> ㅇ ㅜ <SEP> ㄹ ㅣ ㄴ <SEP> <SPC> ㅇ ...,ㄱ ㅡ <SEP> <SPC> ㅇ ㅜ <SEP> ㄹ ㅣ ㄴ <SEP> <SPC> ㅇ ...,60대 이상,DZJD21001967.json,26,train,308.0

In [29]:
jj_jamo_4.to_csv("/workspace/datas/jeju/jeju_dialect_jamo_integration_4.csv")

In [15]:
jj_jamo_5 = jj_jamo[(jj_jamo["토큰 길이"] >= 374) & (jj_jamo["토큰 길이"] < 462)]

jj_jamo_5

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
119333,ㅇ ㅓ <SEP> <SPC> n <SEP> a <SEP> m <SEP> e <SEP...,ㅇ ㅓ <SEP> <SPC> n <SEP> a <SEP> m <SEP> e <SEP...,20대,DZES20000550.json,48,train,433.0
119337,ㅇ ㅓ <SEP> <SPC> ㅇ ㅓ <SEP> . <SEP> <SPC> ㄴ ㅓ <S...,ㅇ ㅓ <SEP> <SPC> ㅇ ㅓ <SEP> . <SEP> <SPC> ㄴ ㅓ <S...,20대,DZES20000550.json,41,train,410.0
119348,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㄱ ㅏ <SEP> ㅈ ㅣ <SEP> ㄱ ㅗ <S...,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㄱ ㅏ <SEP> ㅈ ㅣ <SEP> ㄱ ㅗ <S...,20대,DZES20000550.json,45,train,452.0
119388,ㄸ ㅏ ㅇ <SEP> <SPC> ㄱ ㅏ <SEP> ㄹ ㅏ <SEP> . <SEP> ...,ㄸ ㅏ <SEP> ㄱ ㅗ <SEP> <SPC> ㄱ ㅏ <SEP> ㄹ ㅏ <SEP> ...,20대,DZES20000550.json,47,train,428.0
119425,ㅅ ㅏ ㄹ <SEP> ㅉ ㅏ ㄱ <SEP> <SPC> ㄱ ㅡ <SEP> ㄹ ㅓ ㄴ ...,ㅅ ㅏ ㄹ <SEP> ㅉ ㅏ ㄱ <SEP> <SPC> ㄱ ㅡ <SEP> ㄹ ㅓ ㄴ ...,20대,DZES20000550.json,42,train,403.0
119475,ㄱ ㅡ <SEP> ㄴ ㅑ ㅇ <SEP> <SPC> ㄴ ㅏ ㄴ <SEP> . <SEP...,ㄱ ㅡ <SEP> ㄴ ㅑ ㅇ <SEP> <SPC> ㄴ ㅏ ㄴ <SEP> . <SEP...,20대,DZES20000550.json,42,train,415.0
119522,ㅇ ㅠ <SEP> ㅂ ㅏ ㄹ <SEP> ㅎ ㅏ <SEP> ㄴ ㅡ ㄴ <SEP> <S...,ㅇ ㅠ <SEP> ㅂ ㅏ ㄹ <SEP> ㅎ ㅏ <SEP> ㄴ ㅡ ㄴ <SEP> <S...,20대,DZES20000550.json,38,train,382.0
119562,ㅇ ㅣ <SEP> <SPC> ㄴ ㅏ ㅁ <SEP> ㅈ ㅏ <SEP> ㄱ ㅏ <SEP...,ㅇ ㅣ <SEP> <SPC> ㄴ ㅏ ㅁ <SEP> ㅈ ㅏ <SEP> ㄱ ㅏ <SEP...,20대,DZES20000550.json,38,train,418.0
119760,ㄱ ㅡ <SEP> ㅊ ㅣ <SEP> . <SEP> <SPC> ㄱ ㅡ ㄴ <SEP> ...,ㄱ ㅡ <SEP> ㅊ ㅣ <SEP> . <SEP> <SPC> ㄱ ㅡ ㄴ <SEP> ...,20대,DZES20000551.json,39,train,387.0
119763,ㄱ ㅡ <SEP> ㅊ ㅣ <SEP> . <SEP> <SPC> ㄱ ㅡ <SEP> ㅊ ...,ㄱ ㅡ <SEP> ㅊ ㅣ <SEP> . <SEP> <SPC> ㄱ ㅡ <SEP> ㅊ ...,20대,DZES20000551.json,40,train,393.0
287627,ㅇ ㅓ <SEP> <SPC> ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> <SPC> ㄱ ...,ㅇ ㅓ <SEP> <SPC> ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> <SPC> ㄱ ...,40대,DZES21001730.json,39,train,377.0
292488,ㄱ ㅡ <SEP> ㄱ ㅓ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ㅈ ㅜ <SEP...,ㄱ ㅡ <SEP> ㄱ ㅓ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ㅈ ㅜ <SEP...,30대,DZES21001770.json,41,train,382.0
320168,ㄱ ㅔ ㄴ <SEP> ㄷ ㅣ <SEP> <SPC> ㄴ ㅏ <SEP> <SPC> ㅅ ...,ㄱ ㅡ <SEP> ㄹ ㅓ ㄴ <SEP> ㄷ ㅔ <SEP> <SPC> ㄴ ㅏ <SEP...,60대 이상,DZHF20000027.json,50,train,419.0
320171,ㄱ ㅔ <SEP> ㄴ ㅏ ㄴ <SEP> <SPC> ㅇ ㅜ <SEP> ㄹ ㅣ <SEP...,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㅇ ㅜ <SEP> ...,60대 이상,DZHF20000027.json,41,train,392.0
320172,ㄱ ㅕ ㅇ <SEP> ㅎ ㅏ <SEP> ㄴ ㅏ ㄴ <SEP> <SPC> ㄱ ㅡ <S...,ㄱ ㅡ <SEP> ㄹ ㅓ ㅎ <SEP> ㄱ ㅔ <SEP> <SPC> ㅎ ㅐ <SEP...,60대 이상,DZHF20000027.json,47,train,422.0
320173,ㅇ ㅏ <SEP> ㄷ ㅡ ㄹ <SEP> ㅇ ㅣ <SEP> <SPC> ㅈ ㅏ <SEP...,ㅇ ㅏ <SEP> ㄷ ㅡ ㄹ <SEP> ㅇ ㅣ <SEP> <SPC> ㅈ ㅏ <SEP...,60대 이상,DZHF20000027.json,36,train,384.0
320236,ㅈ ㅓ ㅁ <SEP> ㅈ ㅐ ㅇ <SEP> ㅇ ㅣ <SEP> <SPC> ㅁ ㅏ ㄹ ...,ㅈ ㅓ ㅁ <SEP> ㅈ ㅐ ㅇ <SEP> ㅇ ㅣ <SEP> <SPC> ㅁ ㅏ ㄹ ...,60대 이상,DZHF20000027.json,44,train,401.0
333140,ㅇ ㅏ <SEP> ㄴ ㅣ <SEP> <SPC> ㅇ ㅖ <SEP> ㅈ ㅓ ㄴ <SEP...,ㅇ ㅏ <SEP> ㄴ ㅣ <SEP> <SPC> ㅇ ㅖ <SEP> ㅈ ㅓ ㄴ <SEP...,20대,DZHF20000093.json,36,train,377.0
333239,ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> <SPC> ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <S...,ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> <SPC> ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <S...,20대,DZHF20000093.json,45,train,461.0
333260,ㅇ ㅏ <SEP> ㄴ ㅣ <SEP> <SPC> ㄱ ㅡ <SEP> ㄹ ㅣ <SEP> ...,ㅇ ㅏ <SEP> ㄴ ㅣ <SEP> <SPC> ㄱ ㅡ <SEP> ㄹ ㅣ <SEP> ...,20대,DZHF20000093.json,50,train,454.0
333266,ㅇ ㅓ <SEP> <SPC> ㅁ ㅏ ㅈ <SEP> ㅇ ㅏ <SEP> <SPC> ㅇ ...,ㅇ ㅓ <SEP> <SPC> ㅁ ㅏ ㅈ <SEP> ㅇ ㅏ <SEP> <SPC> ㅇ ...,20대,DZHF20000093.json,43,train,389.0
352318,ㅇ ㅣ <SEP> <SPC> ㄷ ㅡ ㄹ <SEP> ㅇ ㅓ <SEP> ㄱ ㅏ <SEP...,ㅇ ㅣ <SEP> <SPC> ㄷ ㅡ ㄹ <SEP> ㅇ ㅓ <SEP> ㄱ ㅏ <SEP...,20대,DZHF20000175.json,39,train,390.0
614380,ㄱ ㅡ <SEP> ㄹ ㅣ <SEP> ㄱ ㅗ <SEP> <SPC> ㄱ ㅜ <SEP> ...,ㄱ ㅡ <SEP> ㄹ ㅣ <SEP> ㄱ ㅗ <SEP> <SPC> ㄱ ㅜ <SEP> ...,40대,DZHF20001584.json,38,train,374.0
856950,ㅇ ㅜ <SEP> ㄹ ㅣ <SEP> <SPC> ㅅ ㅓ <SEP> ㅂ ㅏ ㅇ <SEP...,ㅇ ㅜ <SEP> ㄹ ㅣ <SEP> <SPC> ㅅ ㅓ <SEP> ㅂ ㅏ ㅇ <SEP...,50대,DZHF20002670.json,44,train,453.0
856988,ㄱ ㅓ <SEP> ㄱ ㅣ <SEP> ㅅ ㅓ <SEP> <SPC> ㅇ ㅣ <SEP> ...,ㄱ ㅓ <SEP> ㄱ ㅣ <SEP> ㅅ ㅓ <SEP> <SPC> ㅇ ㅣ <SEP> ...,50대,DZHF20002670.json,45,train,456.0
857060,ㅁ ㅝ <SEP> <SPC> ㅎ ㅏ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ㅇ ...,ㅁ ㅝ <SEP> <SPC> ㅎ ㅏ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ㅇ ...,50대,DZHF20002670.json,40,train,426.0

In [17]:
print(len(jj_jamo_5[jj_jamo_5["셋"] == "train"]))

26

In [31]:
jj_jamo_5.to_csv("/workspace/datas/jeju/jeju_dialect_jamo_integration_5.csv")

In [32]:
jj_jamo_6 = jj_jamo[(jj_jamo["토큰 길이"] >= 462) & (jj_jamo["토큰 길이"] < 551)]

jj_jamo_6

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
119331,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> <SPC> ㄱ ㅏ <SEP> ㅈ ㅣ <SEP> ...,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> <SPC> ㄱ ㅏ <SEP> ㅈ ㅣ <SEP> ...,20대,DZES20000550.json,46,train,486.0
119426,ㅇ ㅙ <SEP> ㄴ ㅑ <SEP> ㅎ ㅏ <SEP> ㅁ ㅕ ㄴ <SEP> <SPC...,ㅇ ㅙ <SEP> ㄴ ㅑ <SEP> ㅎ ㅏ <SEP> ㅁ ㅕ ㄴ <SEP> <SPC...,20대,DZES20000550.json,52,train,503.0
119476,ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> <SPC> ㅇ ㅛ <SEP> ㅅ ㅐ <SEP...,ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> <SPC> ㅇ ㅛ <SEP> ㅅ ㅐ <SEP...,20대,DZES20000550.json,48,train,506.0
333247,ㅇ ㅏ <SEP> ㄴ ㅣ <SEP> <SPC> ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP...,ㅇ ㅏ <SEP> ㄴ ㅣ <SEP> <SPC> ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP...,20대,DZHF20000093.json,49,train,483.0
856990,ㅂ ㅣ ㅅ <SEP> ㄷ ㅐ <SEP> ㅇ ㅓ <SEP> ㄱ ㅡ <SEP> ㄴ ㅐ ...,ㅂ ㅣ ㅅ <SEP> ㄷ ㅐ <SEP> ㅇ ㅓ <SEP> ㅅ ㅓ <SEP> <SPC...,50대,DZHF20002670.json,53,train,513.0
857053,ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> <SPC> ㄴ ㅏ <SEP> ㄱ ㅏ <SEP...,ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> <SPC> ㄴ ㅏ <SEP> ㄱ ㅏ <SEP...,50대,DZHF20002670.json,51,train,501.0
857061,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㄷ ㅗ <SEP> <SPC> ㄱ ㅡ <SEP> ...,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㄷ ㅗ <SEP> <SPC> ㄱ ㅡ <SEP> ...,50대,DZHF20002670.json,46,train,470.0

In [33]:
jj_jamo_6.to_csv("/workspace/datas/jeju/jeju_dialect_jamo_integration_6.csv")

In [36]:
jj_jamo_7 = jj_jamo[(jj_jamo["토큰 길이"] >= 551) & (jj_jamo["토큰 길이"] < 640)]

jj_jamo_7

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
119413,ㅊ ㅣ ㄹ <SEP> ㅅ ㅣ ㅂ <SEP> ㅍ ㅏ ㄹ <SEP> . <SEP> <S...,ㅊ ㅣ ㄹ <SEP> ㅅ ㅣ ㅂ <SEP> ㅍ ㅏ ㄹ <SEP> . <SEP> <S...,20대,DZES20000550.json,66,train,605.0

In [35]:
jj_jamo_7.to_csv("/workspace/datas/jeju/jeju_dialect_jamo_integration_7.csv")

In [37]:
jj_jamo_8 = jj_jamo[(jj_jamo["토큰 길이"] >= 640) & (jj_jamo["토큰 길이"] < 729)]

jj_jamo_8

Empty DataFrame
Columns: [방언, 표준어, 연령대, 출처 파일, 길이, 셋, 토큰 길이]
Index: []

In [38]:
jj_jamo_9 = jj_jamo[(jj_jamo["토큰 길이"] >= 729) & (jj_jamo["토큰 길이"] < 817)]

jj_jamo_9

Empty DataFrame
Columns: [방언, 표준어, 연령대, 출처 파일, 길이, 셋, 토큰 길이]
Index: []

In [39]:
jj_jamo_10 = jj_jamo[(jj_jamo["토큰 길이"] >= 817)]

jj_jamo_10

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
119416,ㅇ ㅣ <SEP> ㄹ ㅓ ㄴ <SEP> <SPC> ㅅ ㅣ ㄱ <SEP> ㅇ ㅣ <S...,ㅇ ㅣ <SEP> ㄹ ㅓ ㄴ <SEP> <SPC> ㅅ ㅣ ㄱ <SEP> ㅇ ㅣ <S...,20대,DZES20000550.json,88,train,905.0

In [40]:
jj_jamo_10.to_csv("/workspace/datas/jeju/jeju_dialect_jamo_integration_10.csv")

# 충청 방언

In [6]:
cc_jamo = pd.read_csv("/workspace/datas/chungcheong/chungcheong_dialect_jamo_integration.csv", index_col=0)

cc_jamo

,방언,표준어,연령대,출처 파일,길이,셋
0,ㅇ ㅕ ㅇ <SEP> ㅎ ㅘ <SEP> ㅂ ㅗ <SEP> ㄷ ㅏ <SEP> ㄴ ㅡ ...,ㅇ ㅕ ㅇ <SEP> ㅎ ㅘ <SEP> ㅂ ㅗ <SEP> ㄷ ㅏ <SEP> ㄴ ㅡ ...,50대,DCNA20001462.json,6,train
1,ㅇ ㅔ <SEP> ~ <SEP> <SPC> ㅈ ㅓ <SEP> ㄴ ㅡ ㄴ <SEP> ...,ㅇ ㅔ <SEP> ~ <SEP> <SPC> ㅈ ㅓ <SEP> ㄴ ㅡ ㄴ <SEP> ...,20대,DCDG20000795.json,5,train
2,ㄱ ㅡ <SEP> <SPC> c <SEP> o <SEP> m <SEP> p <SEP...,ㄱ ㅡ <SEP> <SPC> c <SEP> o <SEP> m <SEP> p <SEP...,20대,DCDG20001601.json,6,train
3,ㄱ ㅗ <SEP> ㅇ ㅟ <SEP> ㅎ ㅓ ㅁ <SEP> <SPC> ㄱ ㅡ <SEP...,ㄱ ㅗ <SEP> ㅇ ㅟ <SEP> ㅎ ㅓ ㅁ <SEP> <SPC> ㄱ ㅡ <SEP...,40대,DCEX20001058.json,21,train
4,ㅋ ㅗ <SEP> ㄹ ㅗ <SEP> ㄴ ㅏ <SEP> <SPC> ㄸ ㅐ <SEP> ...,ㅋ ㅗ <SEP> ㄹ ㅗ <SEP> ㄴ ㅏ <SEP> <SPC> ㄸ ㅐ <SEP> ...,40대,DCNA20001390.json,9,train
...,...,...,...,...,...,...
227987,ㄴ ㅏ ㅁ <SEP> ㅇ ㅢ <SEP> <SPC> ㅇ ㅣ ㄴ <SEP> ㅈ ㅔ <S...,ㄴ ㅏ ㅁ <SEP> ㅇ ㅢ <SEP> <SPC> ㅇ ㅣ ㄴ <SEP> ㅈ ㅔ <S...,50대,DCNA20000036.json,8,test
227988,ㄱ ㅡ <SEP> <SPC> ㅈ ㅏ ㅂ <SEP> ㅊ ㅗ <SEP> ㄱ ㅏ <SEP...,ㄱ ㅡ <SEP> <SPC> ㅈ ㅏ ㅂ <SEP> ㅊ ㅗ <SEP> ㄱ ㅏ <SEP...,50대,DCNA20000036.json,9,test
227993,ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㅁ ㅕ ㄴ <SEP> ㅅ ㅓ <SEP> <SPC...,ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㅁ ㅕ ㄴ <SEP> ㅅ ㅓ <SEP> <SPC...,50대,DCNA20000036.json,5,test
227994,ㅇ ㅏ <SEP> ㅇ ㅠ <SEP> <SPC> ㅈ ㅓ <SEP> ㄱ ㅣ <SEP> ...,ㅇ ㅏ <SEP> ㅇ ㅠ <SEP> <SPC> ㅈ ㅓ <SEP> ㄱ ㅣ <SEP> ...,50대,DCNA20000036.json,10,test
227995,ㄱ ㅡ <SEP> ㄹ ㅓ ㄴ <SEP> <SPC> ㅁ ㅏ ㄹ <SEP> ㅇ ㅣ <S...,ㄱ ㅡ <SEP> ㄹ ㅓ ㄴ <SEP> <SPC> ㅁ ㅏ ㄹ <SEP> ㅇ ㅣ <S...,50대,DCNA20000036.json,7,test

In [7]:
cc_jamo = cc_jamo.reset_index(drop=True)

In [8]:
seq_len_list = []
for sentence in cc_jamo["방언"].to_list():
    seq_len = len(sentence.split())
    
    seq_len_list.append(seq_len)

cc_jamo.loc[cc_jamo.index, "토큰 길이"] = seq_len_list

cc_jamo

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
0,ㅇ ㅕ ㅇ <SEP> ㅎ ㅘ <SEP> ㅂ ㅗ <SEP> ㄷ ㅏ <SEP> ㄴ ㅡ ...,ㅇ ㅕ ㅇ <SEP> ㅎ ㅘ <SEP> ㅂ ㅗ <SEP> ㄷ ㅏ <SEP> ㄴ ㅡ ...,50대,DCNA20001462.json,6,train,59.0
1,ㅇ ㅔ <SEP> ~ <SEP> <SPC> ㅈ ㅓ <SEP> ㄴ ㅡ ㄴ <SEP> ...,ㅇ ㅔ <SEP> ~ <SEP> <SPC> ㅈ ㅓ <SEP> ㄴ ㅡ ㄴ <SEP> ...,20대,DCDG20000795.json,5,train,47.0
2,ㄱ ㅡ <SEP> <SPC> c <SEP> o <SEP> m <SEP> p <SEP...,ㄱ ㅡ <SEP> <SPC> c <SEP> o <SEP> m <SEP> p <SEP...,20대,DCDG20001601.json,6,train,69.0
3,ㄱ ㅗ <SEP> ㅇ ㅟ <SEP> ㅎ ㅓ ㅁ <SEP> <SPC> ㄱ ㅡ <SEP...,ㄱ ㅗ <SEP> ㅇ ㅟ <SEP> ㅎ ㅓ ㅁ <SEP> <SPC> ㄱ ㅡ <SEP...,40대,DCEX20001058.json,21,train,200.0
4,ㅋ ㅗ <SEP> ㄹ ㅗ <SEP> ㄴ ㅏ <SEP> <SPC> ㄸ ㅐ <SEP> ...,ㅋ ㅗ <SEP> ㄹ ㅗ <SEP> ㄴ ㅏ <SEP> <SPC> ㄸ ㅐ <SEP> ...,40대,DCNA20001390.json,9,train,91.0
...,...,...,...,...,...,...,...
710983,ㄴ ㅏ ㅁ <SEP> ㅇ ㅢ <SEP> <SPC> ㅇ ㅣ ㄴ <SEP> ㅈ ㅔ <S...,ㄴ ㅏ ㅁ <SEP> ㅇ ㅢ <SEP> <SPC> ㅇ ㅣ ㄴ <SEP> ㅈ ㅔ <S...,50대,DCNA20000036.json,8,test,86.0
710984,ㄱ ㅡ <SEP> <SPC> ㅈ ㅏ ㅂ <SEP> ㅊ ㅗ <SEP> ㄱ ㅏ <SEP...,ㄱ ㅡ <SEP> <SPC> ㅈ ㅏ ㅂ <SEP> ㅊ ㅗ <SEP> ㄱ ㅏ <SEP...,50대,DCNA20000036.json,9,test,72.0
710985,ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㅁ ㅕ ㄴ <SEP> ㅅ ㅓ <SEP> <SPC...,ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㅁ ㅕ ㄴ <SEP> ㅅ ㅓ <SEP> <SPC...,50대,DCNA20000036.json,5,test,56.0
710986,ㅇ ㅏ <SEP> ㅇ ㅠ <SEP> <SPC> ㅈ ㅓ <SEP> ㄱ ㅣ <SEP> ...,ㅇ ㅏ <SEP> ㅇ ㅠ <SEP> <SPC> ㅈ ㅓ <SEP> ㄱ ㅣ <SEP> ...,50대,DCNA20000036.json,10,test,87.0
710987,ㄱ ㅡ <SEP> ㄹ ㅓ ㄴ <SEP> <SPC> ㅁ ㅏ ㄹ <SEP> ㅇ ㅣ <S...,ㄱ ㅡ <SEP> ㄹ ㅓ ㄴ <SEP> <SPC> ㅁ ㅏ ㄹ <SEP> ㅇ ㅣ <S...,50대,DCNA20000036.json,7,test,66.0

In [10]:
cc_jamo["토큰 길이"].mean()

96.54796846078978

In [22]:
max(cc_jamo["토큰 길이"].to_list())

415.0

In [23]:
min(cc_jamo["토큰 길이"].to_list())

21.0

구간은 10개. 구간 길이는 415-21=394

구간 한 개는 394 / 10 = 39

- 376-415
- 336-375
- 296-335
- 256-295
- 216-255
- 176-215
- 136-175
- 96-135
- 56-95
- 21-55

In [24]:
cc_jamo_1 = cc_jamo[cc_jamo["토큰 길이"] <= 55]

cc_jamo_1

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
1,ㅇ ㅔ <SEP> ~ <SEP> <SPC> ㅈ ㅓ <SEP> ㄴ ㅡ ㄴ <SEP> ...,ㅇ ㅔ <SEP> ~ <SEP> <SPC> ㅈ ㅓ <SEP> ㄴ ㅡ ㄴ <SEP> ...,20대,DCDG20000795.json,5,train,47.0
16,ㅁ ㅏ ㄱ <SEP> <SPC> ㅇ ㅘ ㅆ <SEP> ㅇ ㅓ <SEP> <SPC> ...,ㅁ ㅏ ㄱ <SEP> <SPC> ㅇ ㅘ ㅆ <SEP> ㅇ ㅓ <SEP> <SPC> ...,50대,DCNA20002386.json,6,train,48.0
31,ㄱ ㅡ <SEP> ㄹ ㅓ ㄴ <SEP> <SPC> ㄱ ㅓ ㄹ <SEP> ㄹ ㅗ <S...,ㄱ ㅡ <SEP> ㄹ ㅓ ㄴ <SEP> <SPC> ㄱ ㅓ ㄹ <SEP> ㄹ ㅗ <S...,20대,DCDG20002053.json,6,train,55.0
39,ㅇ ㅏ ㄴ <SEP> <SPC> ㄷ ㅚ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ...,ㅇ ㅏ ㄴ <SEP> <SPC> ㄷ ㅚ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ...,40대,DCDG20001577.json,5,train,41.0
42,ㄷ ㅜ <SEP> ㅂ ㅜ <SEP> <SPC> ㅁ ㅝ <SEP> <SPC> ㄱ ㅡ ...,ㄷ ㅜ <SEP> ㅂ ㅜ <SEP> <SPC> ㅁ ㅝ <SEP> <SPC> ㄱ ㅡ ...,20대,DCNA20001020.json,6,train,44.0
...,...,...,...,...,...,...,...
710946,ㅊ ㅐ <SEP> ㅅ ㅗ <SEP> ㄹ ㅡ ㄹ <SEP> <SPC> ㅅ ㅣ ㅁ <S...,ㅊ ㅐ <SEP> ㅅ ㅗ <SEP> ㄹ ㅡ ㄹ <SEP> <SPC> ㅅ ㅣ ㅁ <S...,50대,DCNA20000036.json,5,test,46.0
710948,ㅅ ㅣ ㅁ <SEP> ㅇ ㅓ ㅆ <SEP> ㄴ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> ...,ㅅ ㅣ ㅁ <SEP> ㅇ ㅓ ㅆ <SEP> ㄴ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> ...,50대,DCNA20000036.json,6,test,54.0
710956,ㅇ ㅓ <SEP> ~ <SEP> <SPC> ㅉ ㅗ <SEP> ㄲ ㅗ ㅁ <SEP> ...,ㅇ ㅓ <SEP> ~ <SEP> <SPC> ㅈ ㅗ <SEP> ㄱ ㅡ ㅁ <SEP> ...,50대,DCNA20000036.json,5,test,46.0
710960,ㅈ ㅓ <SEP> ㅎ ㅢ <SEP> <SPC> ㅈ ㅣ ㅂ <SEP> ㄷ ㅜ <SEP...,ㅈ ㅓ <SEP> ㅎ ㅢ <SEP> <SPC> ㅈ ㅣ ㅂ <SEP> ㄷ ㅜ <SEP...,50대,DCNA20000036.json,5,test,45.0
710965,ㄸ ㅗ <SEP> <SPC> ㅅ ㅣ <SEP> ㄱ ㅗ ㄹ <SEP> ㅇ ㅔ <SEP...,ㄸ ㅗ <SEP> <SPC> ㅅ ㅣ <SEP> ㄱ ㅗ ㄹ <SEP> ㅇ ㅔ <SEP...,50대,DCNA20000036.json,5,test,49.0

In [25]:
cc_jamo_1[cc_jamo_1["셋"] == "train"]

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
1,ㅇ ㅔ <SEP> ~ <SEP> <SPC> ㅈ ㅓ <SEP> ㄴ ㅡ ㄴ <SEP> ...,ㅇ ㅔ <SEP> ~ <SEP> <SPC> ㅈ ㅓ <SEP> ㄴ ㅡ ㄴ <SEP> ...,20대,DCDG20000795.json,5,train,47.0
16,ㅁ ㅏ ㄱ <SEP> <SPC> ㅇ ㅘ ㅆ <SEP> ㅇ ㅓ <SEP> <SPC> ...,ㅁ ㅏ ㄱ <SEP> <SPC> ㅇ ㅘ ㅆ <SEP> ㅇ ㅓ <SEP> <SPC> ...,50대,DCNA20002386.json,6,train,48.0
31,ㄱ ㅡ <SEP> ㄹ ㅓ ㄴ <SEP> <SPC> ㄱ ㅓ ㄹ <SEP> ㄹ ㅗ <S...,ㄱ ㅡ <SEP> ㄹ ㅓ ㄴ <SEP> <SPC> ㄱ ㅓ ㄹ <SEP> ㄹ ㅗ <S...,20대,DCDG20002053.json,6,train,55.0
39,ㅇ ㅏ ㄴ <SEP> <SPC> ㄷ ㅚ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ...,ㅇ ㅏ ㄴ <SEP> <SPC> ㄷ ㅚ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ...,40대,DCDG20001577.json,5,train,41.0
42,ㄷ ㅜ <SEP> ㅂ ㅜ <SEP> <SPC> ㅁ ㅝ <SEP> <SPC> ㄱ ㅡ ...,ㄷ ㅜ <SEP> ㅂ ㅜ <SEP> <SPC> ㅁ ㅝ <SEP> <SPC> ㄱ ㅡ ...,20대,DCNA20001020.json,6,train,44.0
...,...,...,...,...,...,...,...
520946,ㅇ ㅓ <SEP> ~ <SEP> <SPC> ㄱ ㅡ <SEP> ㄹ ㅓ ㄴ <SEP> ...,ㅇ ㅓ <SEP> ~ <SEP> <SPC> ㄱ ㅡ <SEP> ㄹ ㅓ ㄴ <SEP> ...,40대,DCDG20001932.json,6,train,39.0
520950,ㄴ ㅏ <SEP> ㄹ ㅏ ㅇ <SEP> <SPC> ㄱ ㅏ ㅌ <SEP> ㅇ ㅣ <S...,ㄴ ㅏ <SEP> ㄹ ㅏ ㅇ <SEP> <SPC> ㄱ ㅏ ㅌ <SEP> ㅇ ㅣ <S...,20대,DCNA20001023.json,5,train,40.0
520954,ㄱ ㅡ <SEP> ㄹ ㅓ ㄴ <SEP> <SPC> ㄷ ㅔ <SEP> ㅅ ㅓ <SEP...,ㄱ ㅡ <SEP> ㄹ ㅓ ㄴ <SEP> <SPC> ㄷ ㅔ <SEP> ㅅ ㅓ <SEP...,50대,DCNA20001373.json,7,train,55.0
520961,ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> <SPC> ㄱ ㅡ <SEP> ㄱ ㅓ <SEP...,ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> <SPC> ㄱ ㅡ <SEP> ㄱ ㅓ <SEP...,20대,DCEX20010173.json,5,train,38.0
520972,ㅎ ㅕ ㅇ <SEP> ㅂ ㅜ <SEP> <SPC> ㄸ ㅐ <SEP> ㅁ ㅜ ㄴ <S...,ㅎ ㅕ ㅇ <SEP> ㅂ ㅜ <SEP> <SPC> ㄸ ㅐ <SEP> ㅁ ㅜ ㄴ <S...,30대,DCNA20001400.json,6,train,52.0

In [26]:
cc_jamo_1.to_csv("/workspace/datas/chungcheong/chungcheong_dialect_jamo_integration_1.csv")

In [28]:
cc_jamo_2 = cc_jamo[(cc_jamo["토큰 길이"] >= 56) & (cc_jamo["토큰 길이"] < 96)]

cc_jamo_2.to_csv("/workspace/datas/chungcheong/chungcheong_dialect_jamo_integration_2.csv")

cc_jamo_2[cc_jamo_2["셋"] == "train"]

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
0,ㅇ ㅕ ㅇ <SEP> ㅎ ㅘ <SEP> ㅂ ㅗ <SEP> ㄷ ㅏ <SEP> ㄴ ㅡ ...,ㅇ ㅕ ㅇ <SEP> ㅎ ㅘ <SEP> ㅂ ㅗ <SEP> ㄷ ㅏ <SEP> ㄴ ㅡ ...,50대,DCNA20001462.json,6,train,59.0
2,ㄱ ㅡ <SEP> <SPC> c <SEP> o <SEP> m <SEP> p <SEP...,ㄱ ㅡ <SEP> <SPC> c <SEP> o <SEP> m <SEP> p <SEP...,20대,DCDG20001601.json,6,train,69.0
4,ㅋ ㅗ <SEP> ㄹ ㅗ <SEP> ㄴ ㅏ <SEP> <SPC> ㄸ ㅐ <SEP> ...,ㅋ ㅗ <SEP> ㄹ ㅗ <SEP> ㄴ ㅏ <SEP> <SPC> ㄸ ㅐ <SEP> ...,40대,DCNA20001390.json,9,train,91.0
6,ㅇ ㅛ <SEP> ㅂ ㅓ ㄴ <SEP> ㅇ ㅔ <SEP> <SPC> ㄱ ㅡ <SEP...,ㅇ ㅛ <SEP> ㅂ ㅓ ㄴ <SEP> ㅇ ㅔ <SEP> <SPC> ㄱ ㅡ <SEP...,40대,DCNA20002160.json,10,train,84.0
8,ㅁ ㅝ <SEP> <SPC> ㅅ ㅣ ㄹ <SEP> ㄱ ㅣ <SEP> ㅇ ㅔ <SEP...,ㅁ ㅝ <SEP> <SPC> ㅅ ㅣ ㄹ <SEP> ㄱ ㅣ <SEP> ㅇ ㅔ <SEP...,30대,DCDG20001186.json,7,train,71.0
...,...,...,...,...,...,...,...
520980,ㅉ ㅗ ㅁ <SEP> <SPC> ㅎ ㅘ <SEP> ㄹ ㅡ ㄹ <SEP> <SPC> ...,ㅈ ㅗ <SEP> ㄱ ㅡ ㅁ <SEP> <SPC> ㅎ ㅘ <SEP> ㄹ ㅡ ㄹ <S...,20대,DCDG20001304.json,12,train,92.0
520982,ㅇ ㅑ <SEP> <SPC> ㅌ ㅏ <SEP> <SPC> ㄱ ㅡ <SEP> ㄹ ㅐ ...,ㅇ ㅑ <SEP> <SPC> ㅌ ㅏ <SEP> <SPC> ㄱ ㅡ <SEP> ㄹ ㅐ ...,40대,DCNA20000108.json,10,train,95.0
520984,ㄱ ㅡ <SEP> ~ <SEP> <SPC> ㅇ ㅛ ㄱ <SEP> ㅅ ㅣ ㅁ <SEP...,ㄱ ㅡ <SEP> ~ <SEP> <SPC> ㅇ ㅛ ㄱ <SEP> ㅅ ㅣ ㅁ <SEP...,60대 이상,DCNA20001459.json,7,train,63.0
520985,ㄱ ㅡ <SEP> ~ <SEP> <SPC> ㄴ ㅏ ㅈ <SEP> ㅇ ㅏ <SEP> ...,ㄱ ㅡ <SEP> ~ <SEP> <SPC> ㄴ ㅏ ㅈ <SEP> ㅇ ㅏ <SEP> ...,50대,DCDG20000849.json,9,train,69.0
520986,ㅅ ㅏ <SEP> ㄹ ㅏ ㅁ <SEP> ㄷ ㅡ ㄹ <SEP> <SPC> ㅋ ㅟ ㄴ ...,ㅅ ㅏ <SEP> ㄹ ㅏ ㅁ <SEP> ㄷ ㅡ ㄹ <SEP> <SPC> ㅋ ㅟ ㄴ ...,20대,DCNA20000770.json,7,train,92.0

In [29]:
cc_jamo_3 = cc_jamo[(cc_jamo["토큰 길이"] >= 96) & (cc_jamo["토큰 길이"] < 136)]

cc_jamo_3.to_csv("/workspace/datas/chungcheong/chungcheong_dialect_jamo_integration_3.csv")

cc_jamo_3[cc_jamo_3["셋"] == "train"]

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
5,n <SEP> a <SEP> m <SEP> e <SEP> ㅇ ㅣ <SEP> ㄴ ㅡ ...,n <SEP> a <SEP> m <SEP> e <SEP> ㅇ ㅣ <SEP> ㄴ ㅡ ...,40대,DCDG20001188.json,11,train,102.0
7,ㅎ ㅐ <SEP> <SPC> ㄷ ㅏ ㄹ <SEP> ㄹ ㅏ <SEP> ㄱ ㅗ <SEP...,ㅎ ㅐ <SEP> <SPC> ㄷ ㅏ ㄹ <SEP> ㄹ ㅏ <SEP> ㄱ ㅗ <SEP...,60대 이상,DCNA20001744.json,14,train,134.0
12,ㄴ ㅐ <SEP> ㄱ ㅏ <SEP> <SPC> ㅅ ㅓ ㅇ <SEP> ㄷ ㅏ ㅇ <S...,ㄴ ㅐ <SEP> ㄱ ㅏ <SEP> <SPC> ㅅ ㅓ ㅇ <SEP> ㄷ ㅏ ㅇ <S...,60대 이상,DCDG20002394.json,12,train,125.0
15,ㅇ ㅓ <SEP> <SPC> ㄱ ㅡ ㅇ <SEP> ㄲ ㅏ <SEP> <SPC> ㄱ ...,ㅇ ㅓ <SEP> <SPC> ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㄴ ㅣ <SEP> ...,20대,DCNA20000457.json,12,train,122.0
17,ㅇ ㅣ ㄴ <SEP> ㅈ ㅏ <SEP> <SPC> ㄱ ㅡ <SEP> <SPC> ㄱ ...,ㅇ ㅣ <SEP> ㅈ ㅔ <SEP> <SPC> ㄱ ㅡ <SEP> <SPC> ㄱ ㅛ ...,50대,DCNA20000160.json,13,train,125.0
...,...,...,...,...,...,...,...
520976,ㅎ ㅏ ㄴ <SEP> <SPC> ㄷ ㅏ ㄹ <SEP> <SPC> ㄷ ㅗ ㅇ <SEP...,ㅎ ㅏ ㄴ <SEP> <SPC> ㄷ ㅏ ㄹ <SEP> <SPC> ㄷ ㅗ ㅇ <SEP...,20대,DCNA20000374.json,14,train,121.0
520978,ㅈ ㅣ ㅂ <SEP> ㅈ ㅣ ㅂ <SEP> ㅁ ㅏ <SEP> ㄷ ㅏ <SEP> <S...,ㅈ ㅣ ㅂ <SEP> ㅈ ㅣ ㅂ <SEP> ㅁ ㅏ <SEP> ㄷ ㅏ <SEP> <S...,60대 이상,DCNA20001338.json,12,train,107.0
520979,ㄴ ㅏ <SEP> ㄹ ㅏ ㅇ <SEP> <SPC> ㄸ ㅗ ㄱ <SEP> ㄱ ㅏ ㅌ ...,ㄴ ㅏ <SEP> ㄹ ㅏ ㅇ <SEP> <SPC> ㄸ ㅗ ㄱ <SEP> ㄱ ㅏ ㅌ ...,60대 이상,DCNA20002085.json,11,train,118.0
520981,ㄷ ㅏ <SEP> ㄹ ㅡ ㄴ <SEP> <SPC> ㅂ ㅏ ㅇ <SEP> ㅇ ㅏ ㄴ ...,ㄷ ㅏ <SEP> ㄹ ㅡ ㄴ <SEP> <SPC> ㅂ ㅏ ㅇ <SEP> ㅇ ㅏ ㄴ ...,20대,DCEX20002100.json,11,train,116.0
520983,ㄱ ㅓ <SEP> ㄱ ㅣ <SEP> ㅅ ㅓ <SEP> <SPC> ㅂ ㅏ ㅂ <SEP...,ㄱ ㅓ <SEP> ㄱ ㅣ <SEP> ㅅ ㅓ <SEP> <SPC> ㅂ ㅏ ㅂ <SEP...,60대 이상,DCNA20001746.json,15,train,115.0

In [30]:
cc_jamo_4 = cc_jamo[(cc_jamo["토큰 길이"] >= 136) & (cc_jamo["토큰 길이"] < 176)]

cc_jamo_4.to_csv("/workspace/datas/chungcheong/chungcheong_dialect_jamo_integration_4.csv")

cc_jamo_4[cc_jamo_4["셋"] == "train"]

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
11,ㄷ ㅐ <SEP> ㅍ ㅛ <SEP> ㄴ ㅏ <SEP> <SPC> ㅎ ㅚ <SEP> ...,ㄷ ㅐ <SEP> ㅍ ㅛ <SEP> ㄴ ㅏ <SEP> <SPC> ㅎ ㅚ <SEP> ...,30대,DCNA20000902.json,16,train,143.0
14,ㅇ ㅓ ㄴ <SEP> ㄴ ㅣ <SEP> ㅎ ㅏ ㄴ <SEP> ㅌ ㅔ <SEP> <S...,ㅇ ㅓ ㄴ <SEP> ㄴ ㅣ <SEP> ㅎ ㅏ ㄴ <SEP> ㅌ ㅔ <SEP> <S...,50대,DCNA20001489.json,13,train,137.0
20,ㄷ ㅓ <SEP> <SPC> ㅇ ㅕ <SEP> ㅇ ㅠ <SEP> ㄱ ㅏ <SEP> ...,ㄷ ㅓ <SEP> <SPC> ㅇ ㅕ <SEP> ㅇ ㅠ <SEP> ㄱ ㅏ <SEP> ...,20대,DCNA20001102.json,17,train,143.0
24,ㄸ ㅗ <SEP> <SPC> ㅅ ㅐ <SEP> ㄹ ㅗ <SEP> ㅇ ㅜ ㄴ <SEP...,ㄸ ㅗ <SEP> <SPC> ㅅ ㅐ <SEP> ㄹ ㅗ <SEP> ㅇ ㅜ ㄴ <SEP...,10대,DCDG20002409.json,20,train,149.0
25,ㅇ ㅓ <SEP> ~ <SEP> <SPC> ㅁ ㅝ <SEP> ~ <SEP> <SPC...,ㅇ ㅓ <SEP> ~ <SEP> <SPC> ㅁ ㅝ <SEP> ~ <SEP> <SPC...,20대,DCEX20002172.json,17,train,165.0
...,...,...,...,...,...,...,...
520941,ㄴ ㅐ <SEP> ㄱ ㅏ <SEP> <SPC> ㄸ ㅗ <SEP> <SPC> ㄴ ㅜ ...,ㄴ ㅐ <SEP> ㄱ ㅏ <SEP> <SPC> ㄸ ㅗ <SEP> <SPC> ㄴ ㅜ ...,60대 이상,DCNA20000825.json,16,train,141.0
520944,ㄱ ㅓ <SEP> ㄱ ㅣ <SEP> <SPC> ㅇ ㅏ ㄵ <SEP> ㅇ ㅏ ㅆ <S...,ㄱ ㅓ <SEP> ㄱ ㅣ <SEP> <SPC> ㅇ ㅏ ㄵ <SEP> ㅇ ㅏ ㅆ <S...,60대 이상,DCNA20000784.json,16,train,155.0
520951,ㄴ ㅐ <SEP> <SPC> ㅊ ㅣ ㄴ <SEP> ㄱ ㅜ <SEP> ㄱ ㅏ <SEP...,ㄴ ㅐ <SEP> <SPC> ㅊ ㅣ ㄴ <SEP> ㄱ ㅜ <SEP> ㄱ ㅏ <SEP...,20대,DCNA20001756.json,20,train,165.0
520965,ㅇ ㅓ <SEP> ~ <SEP> <SPC> ㅇ ㅙ <SEP> ㄴ ㅑ <SEP> ㅁ ...,ㅇ ㅓ <SEP> ~ <SEP> <SPC> ㅇ ㅙ <SEP> ㄴ ㅑ <SEP> ㅁ ...,20대,DCEX20002159.json,14,train,137.0
520969,ㅁ ㅐ ㄴ <SEP> ㄴ ㅏ ㄹ <SEP> <SPC> ㄴ ㅏ <SEP> ㅎ ㅏ ㄴ ...,ㅁ ㅐ ㄴ <SEP> ㄴ ㅏ ㄹ <SEP> <SPC> ㄴ ㅏ <SEP> ㅎ ㅏ ㄴ ...,30대,DCDG20003416.json,12,train,145.0

In [31]:
cc_jamo_5 = cc_jamo[(cc_jamo["토큰 길이"] >= 176) & (cc_jamo["토큰 길이"] < 216)]

cc_jamo_5.to_csv("/workspace/datas/chungcheong/chungcheong_dialect_jamo_integration_5.csv")

cc_jamo_5[cc_jamo_5["셋"] == "train"]

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
3,ㄱ ㅗ <SEP> ㅇ ㅟ <SEP> ㅎ ㅓ ㅁ <SEP> <SPC> ㄱ ㅡ <SEP...,ㄱ ㅗ <SEP> ㅇ ㅟ <SEP> ㅎ ㅓ ㅁ <SEP> <SPC> ㄱ ㅡ <SEP...,40대,DCEX20001058.json,21,train,200.0
30,ㄷ ㅏ <SEP> ㅎ ㅐ ㅇ <SEP> ㅎ ㅣ <SEP> <SPC> ㅇ ㅏ ㄴ <S...,ㄷ ㅏ <SEP> ㅎ ㅐ ㅇ <SEP> ㅎ ㅣ <SEP> <SPC> ㅇ ㅏ ㄴ <S...,10대,DCDG20001111.json,20,train,190.0
32,<SPC> ㄱ ㅡ <SEP> ㄹ ㅐ ㅆ <SEP> ㅇ ㅓ ㅆ <SEP> ㄴ ㅡ ㄴ ...,<SPC> ㄱ ㅡ <SEP> ㄹ ㅐ ㅆ <SEP> ㅇ ㅓ ㅆ <SEP> ㄴ ㅡ ㄴ ...,20대,DCEX20001045.json,19,train,190.0
96,ㅁ ㅜ ㄹ <SEP> ㅇ ㅓ <SEP> ㅂ ㅗ ㄴ <SEP> <SPC> ㅅ ㅏ <S...,ㅁ ㅜ ㄹ <SEP> ㅇ ㅓ <SEP> ㅂ ㅗ ㄴ <SEP> <SPC> ㅅ ㅏ <S...,20대,DCEX20002402.json,22,train,209.0
111,ㅈ ㅓ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ㅉ ㅗ <SEP> ㄲ ㅡ ㅁ <S...,ㅈ ㅓ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ㅈ ㅗ <SEP> ㄱ ㅡ ㅁ <S...,30대,DCEX20020040.json,19,train,196.0
...,...,...,...,...,...,...,...
520770,ㄱ ㅡ <SEP> ㄸ ㅐ <SEP> ㄱ ㅏ <SEP> <SPC> ㄸ ㅏ ㄱ <SEP...,ㄱ ㅡ <SEP> ㄸ ㅐ <SEP> ㄱ ㅏ <SEP> <SPC> ㄸ ㅏ ㄱ <SEP...,20대,DCDG20002416.json,18,train,180.0
520786,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㄴ ㅏ <SEP> ...,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㄴ ㅏ <SEP> ...,20대,DCEX20002290.json,22,train,197.0
520822,ㅅ ㅗ ㄴ <SEP> <SPC> ㅁ ㅏ ㄱ <SEP> <SPC> ㄱ ㅡ <SEP> ...,ㅅ ㅗ ㄴ <SEP> <SPC> ㅁ ㅏ ㄱ <SEP> <SPC> ㄱ ㅡ <SEP> ...,10대,DCDG20001111.json,23,train,187.0
520864,ㅇ ㅣ <SEP> ㅈ ㅔ <SEP> <SPC> ㅇ ㅛ <SEP> ㅈ ㅡ ㅁ <SEP...,ㅇ ㅣ <SEP> ㅈ ㅔ <SEP> <SPC> ㅇ ㅛ <SEP> ㅈ ㅡ ㅁ <SEP...,10대,DCDG20003321.json,19,train,187.0
520987,ㄱ ㅡ <SEP> ㄴ ㅏ <SEP> ㅁ ㅏ <SEP> <SPC> ㅂ ㅏ ㄹ <SEP...,ㄱ ㅡ <SEP> ㄴ ㅏ <SEP> ㅁ ㅏ <SEP> <SPC> ㅂ ㅏ ㄹ <SEP...,20대,DCDG20000580.json,18,train,178.0

In [32]:
cc_jamo_6 = cc_jamo[(cc_jamo["토큰 길이"] >= 216) & (cc_jamo["토큰 길이"] < 256)]

cc_jamo_6.to_csv("/workspace/datas/chungcheong/chungcheong_dialect_jamo_integration_6.csv")

cc_jamo_6[cc_jamo_6["셋"] == "train"]

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
64,ㅁ ㅏ ㄴ <SEP> ㅇ ㅑ ㄱ <SEP> ㅇ ㅔ <SEP> <SPC> ㅇ ㅛ <S...,ㅁ ㅏ ㄴ <SEP> ㅇ ㅑ ㄱ <SEP> ㅇ ㅔ <SEP> <SPC> ㅇ ㅛ <S...,30대,DCDG20000906.json,24,train,246.0
108,ㅇ ㅣ <SEP> ㄷ ㅏ ㄴ <SEP> <SPC> ㄱ ㅛ <SEP> ㅎ ㅚ <SEP...,ㅇ ㅣ <SEP> ㄷ ㅏ ㄴ <SEP> <SPC> ㄱ ㅛ <SEP> ㅎ ㅚ <SEP...,60대 이상,DCDG20002078.json,24,train,221.0
1033,ㅇ ㅓ <SEP> ~ <SEP> <SPC> ㄱ ㅡ <SEP> ~ <SEP> <SPC...,ㅇ ㅓ <SEP> ~ <SEP> <SPC> ㄱ ㅡ <SEP> ~ <SEP> <SPC...,60대 이상,DCNA20001148.json,25,train,216.0
1055,ㅇ ㅛ <SEP> ㅈ ㅡ ㅁ <SEP> ㅇ ㅡ ㄴ <SEP> <SPC> ㅉ ㅗ ㅁ ...,ㅇ ㅛ <SEP> ㅈ ㅡ ㅁ <SEP> ㅇ ㅡ ㄴ <SEP> <SPC> ㅈ ㅗ ㅁ ...,20대,DCEX20002290.json,27,train,222.0
1206,ㅇ ㅛ <SEP> ㅈ ㅡ ㅁ <SEP> ㅇ ㅔ <SEP> ㄴ ㅡ ㄴ <SEP> <S...,ㅇ ㅛ <SEP> ㅈ ㅡ ㅁ <SEP> ㅇ ㅔ <SEP> ㄴ ㅡ ㄴ <SEP> <S...,20대,DCDG20001510.json,22,train,217.0
...,...,...,...,...,...,...,...
519903,ㅁ ㅏ ㄱ <SEP> <SPC> ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> <SPC> ...,ㅁ ㅏ ㄱ <SEP> <SPC> ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> <SPC> ...,20대,DCDG20001589.json,29,train,240.0
519955,ㅇ ㅕ ㄴ <SEP> ㅈ ㅐ <SEP> ㅎ ㅏ ㄹ <SEP> <SPC> ㄸ ㅐ <S...,ㅇ ㅕ ㄴ <SEP> ㅈ ㅐ <SEP> ㅎ ㅏ ㄹ <SEP> <SPC> ㄸ ㅐ <S...,10대,DCDG20003029.json,24,train,227.0
520269,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㅊ ㅣ ㄴ <SEP...,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㅊ ㅣ ㄴ <SEP...,60대 이상,DCNA20002115.json,22,train,219.0
520380,ㅈ ㅔ <SEP> ㄱ ㅏ <SEP> <SPC> ㅊ ㅏ <SEP> ㅁ ㅏ <SEP> ...,ㅈ ㅔ <SEP> ㄱ ㅏ <SEP> <SPC> ㅊ ㅏ <SEP> ㅁ ㅏ <SEP> ...,40대,DCDG20003259.json,27,train,241.0
520800,ㄱ ㅡ ㅇ <SEP> ㄲ ㅏ <SEP> ㄴ ㅡ ㄴ <SEP> <SPC> ㅂ ㅣ <S...,ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㄴ ㅣ <SEP> ㄲ ㅏ <SEP> ㄴ ㅡ ㄴ ...,40대,DCNA20000574.json,22,train,216.0

In [33]:
cc_jamo_7 = cc_jamo[(cc_jamo["토큰 길이"] >= 256) & (cc_jamo["토큰 길이"] < 296)]

cc_jamo_7.to_csv("/workspace/datas/chungcheong/chungcheong_dialect_jamo_integration_7.csv")

cc_jamo_7[cc_jamo_7["셋"] == "train"]

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
4643,ㄴ ㅐ ㅆ <SEP> ㅇ ㅓ <SEP> <SPC> ㄱ ㅏ <SEP> ㅁ ㅏ ㄴ <S...,ㄴ ㅐ ㅆ <SEP> ㅇ ㅓ <SEP> <SPC> ㄱ ㅏ <SEP> ㅁ ㅏ ㄴ <S...,60대 이상,DCNA20002125.json,27,train,265.0
7685,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㅇ ㅣ <SEP> ...,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㅇ ㅣ <SEP> ...,20대,DCDG20001590.json,28,train,287.0
12408,ㄱ ㅗ <SEP> ㅇ ㅑ ㅇ <SEP> ㅇ ㅣ <SEP> ㄷ ㅗ <SEP> <SPC...,ㄱ ㅗ <SEP> ㅇ ㅑ ㅇ <SEP> ㅇ ㅣ <SEP> ㄷ ㅗ <SEP> <SPC...,10대,DCDG20001520.json,26,train,266.0
13617,ㅁ ㅝ <SEP> ~ <SEP> <SPC> ㄱ ㅡ <SEP> <SPC> ㅈ ㅓ ㅇ ...,ㅁ ㅝ <SEP> ~ <SEP> <SPC> ㄱ ㅡ <SEP> <SPC> ㅈ ㅓ ㅇ ...,20대,DCEX20002287.json,33,train,257.0
14719,ㅁ ㅏ ㄱ <SEP> <SPC> ㄱ ㅖ <SEP> ㅅ ㅗ ㄱ <SEP> <SPC> ...,ㅁ ㅏ ㄱ <SEP> <SPC> ㄱ ㅖ <SEP> ㅅ ㅗ ㄱ <SEP> <SPC> ...,20대,DCEX20001038.json,30,train,289.0
...,...,...,...,...,...,...,...
477163,ㄱ ㅡ ㅇ <SEP> ㄲ ㅏ <SEP> <SPC> ㄴ ㅏ <SEP> <SPC> ㄸ ...,ㄱ ㅡ <SEP> ㄹ ㅓ <SEP> ㄴ ㅣ <SEP> ㄲ ㅏ <SEP> <SPC> ...,20대,DCEX20001050.json,33,train,271.0
490428,ㄱ ㅡ <SEP> ㄴ ㅣ <SEP> ㄲ ㅏ <SEP> <SPC> ㅇ ㅣ <SEP> ...,ㄱ ㅡ <SEP> ㄴ ㅣ <SEP> ㄲ ㅏ <SEP> <SPC> ㅇ ㅣ <SEP> ...,20대,DCEX20000121.json,25,train,274.0
493518,ㅇ ㅏ <SEP> ~ <SEP> <SPC> ㄱ ㅡ <SEP> ㄴ ㅑ ㅇ <SEP> ...,ㅇ ㅏ <SEP> ~ <SEP> <SPC> ㄱ ㅡ <SEP> ㄴ ㅑ ㅇ <SEP> ...,30대,DCNA20002449.json,31,train,259.0
504040,ㅇ ㅠ <SEP> ㅈ ㅓ ㄴ <SEP> ㅈ ㅏ <SEP> <SPC> ㄱ ㅓ ㅁ <S...,ㅇ ㅠ <SEP> ㅈ ㅓ ㄴ <SEP> ㅈ ㅏ <SEP> <SPC> ㄱ ㅓ ㅁ <S...,50대,DCNA20001679.json,28,train,272.0
520787,ㅇ ㅓ <SEP> ~ <SEP> <SPC> ㄱ ㅡ <SEP> ㄹ ㅓ ㅎ <SEP> ...,ㅇ ㅓ <SEP> ~ <SEP> <SPC> ㄱ ㅡ <SEP> ㄹ ㅓ ㅎ <SEP> ...,40대,DCEX20020082.json,25,train,263.0

In [35]:
cc_jamo_8 = cc_jamo[(cc_jamo["토큰 길이"] >= 296) & (cc_jamo["토큰 길이"] < 336)]

cc_jamo_8.to_csv("/workspace/datas/chungcheong/chungcheong_dialect_jamo_integration_8.csv")

print(len(cc_jamo_8[cc_jamo_8["셋"] == "train"]))

13

In [36]:
cc_jamo_9 = cc_jamo[(cc_jamo["토큰 길이"] >= 336) & (cc_jamo["토큰 길이"] < 376)]

cc_jamo_9.to_csv("/workspace/datas/chungcheong/chungcheong_dialect_jamo_integration_9.csv")

print(len(cc_jamo_9[cc_jamo_9["셋"] == "train"]))

5

In [37]:
cc_jamo_10 = cc_jamo[(cc_jamo["토큰 길이"] >= 376) & (cc_jamo["토큰 길이"] < 416)]

cc_jamo_10.to_csv("/workspace/datas/chungcheong/chungcheong_dialect_jamo_integration_10.csv")

print(len(cc_jamo_10[cc_jamo_10["셋"] == "train"]))

4

# 강원 방언

In [13]:
gw_jamo = pd.read_csv("/workspace/datas/gangwon/gangwon_dialect_jamo_integration.csv", index_col=0)

gw_jamo

,방언,표준어,연령대,출처 파일,길이,셋
6,ㅂ ㅏ <SEP> ㄷ ㅏ <SEP> ㅇ ㅢ <SEP> <SPC> ㅁ ㅜ <SEP> ...,ㅂ ㅏ <SEP> ㄷ ㅏ <SEP> ㅇ ㅢ <SEP> <SPC> ㅁ ㅜ <SEP> ...,60대 이상,DGDQ20000020.json,5,train
10,ㅇ ㅖ ㅅ <SEP> ㄴ ㅏ ㄹ <SEP> ㅇ ㅔ <SEP> <SPC> ㅂ ㅏ <S...,ㅇ ㅖ ㅅ <SEP> ㄴ ㅏ ㄹ <SEP> ㅇ ㅔ <SEP> <SPC> ㅂ ㅏ <S...,60대 이상,DGDQ20000020.json,8,train
13,ㄱ ㅜ <SEP> ㅅ ㅣ ㅂ <SEP> <SPC> ㅁ ㅕ ㅊ <SEP> <SPC> ...,ㄱ ㅜ <SEP> ㅅ ㅣ ㅂ <SEP> <SPC> ㅁ ㅕ ㅊ <SEP> <SPC> ...,60대 이상,DGDQ20000020.json,5,train
14,ㄱ ㅡ <SEP> ㄸ ㅐ <SEP> ㄱ ㅏ <SEP> <SPC> ㅇ ㅔ ㅁ <SEP...,ㄱ ㅡ <SEP> ㄸ ㅐ <SEP> ㄱ ㅏ <SEP> <SPC> ㅇ ㅔ ㅁ <SEP...,60대 이상,DGDQ20000020.json,9,train
15,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㅇ ㅔ ㅁ <SEP...,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㅇ ㅔ ㅁ <SEP...,60대 이상,DGDQ20000020.json,10,train
...,...,...,...,...,...,...
276791,ㅇ ㅣ ㄴ <SEP> ㅈ ㅔ <SEP> <SPC> ㄱ ㅚ <SEP> ㄱ ㅣ <SEP...,ㅇ ㅣ ㄴ <SEP> ㅈ ㅔ <SEP> <SPC> ㄱ ㅗ <SEP> ㄱ ㅣ <SEP...,30대,DGIN21801133.json,10,test
276792,ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> <SPC> ㅈ ㅣ ㄹ <SEP> ㅇ ㅣ <S...,ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> <SPC> ㅈ ㅣ ㄹ <SEP> ㅇ ㅣ <S...,30대,DGIN21801133.json,6,test
276794,ㅇ ㅓ <SEP> ㄹ ㅕ ㅆ <SEP> ㅇ ㅡ ㄹ <SEP> <SPC> ㄸ ㅐ <S...,ㅇ ㅓ <SEP> ㄹ ㅕ ㅆ <SEP> ㅇ ㅡ ㄹ <SEP> <SPC> ㄸ ㅐ <S...,30대,DGIN21801133.json,13,test
276796,ㅁ ㅓ ㄱ <SEP> ㅇ ㅓ ㅆ <SEP> ㅇ ㅓ ㅆ <SEP> ㄷ ㅓ ㄴ <SEP...,ㅁ ㅓ ㄱ <SEP> ㅇ ㅓ ㅆ <SEP> ㅇ ㅓ ㅆ <SEP> ㄷ ㅓ ㄴ <SEP...,30대,DGIN21801133.json,15,test
276797,ㄴ ㅐ <SEP> ㄱ ㅏ <SEP> <SPC> ㅇ ㅣ ㄹ <SEP> ㅇ ㅡ ㄹ <S...,ㄴ ㅐ <SEP> ㄱ ㅏ <SEP> <SPC> ㅇ ㅣ ㄹ <SEP> ㅇ ㅡ ㄹ <S...,30대,DGIN21801133.json,11,test

In [14]:
gw_jamo = gw_jamo.reset_index(drop=True)

seq_len_list = []
for sentence in gw_jamo["방언"].to_list():
    seq_len = len(sentence.split())
    
    seq_len_list.append(seq_len)

gw_jamo.loc[gw_jamo.index, "토큰 길이"] = seq_len_list

gw_jamo

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
0,ㅂ ㅏ <SEP> ㄷ ㅏ <SEP> ㅇ ㅢ <SEP> <SPC> ㅁ ㅜ <SEP> ...,ㅂ ㅏ <SEP> ㄷ ㅏ <SEP> ㅇ ㅢ <SEP> <SPC> ㅁ ㅜ <SEP> ...,60대 이상,DGDQ20000020.json,5,train,44.0
1,ㅇ ㅖ ㅅ <SEP> ㄴ ㅏ ㄹ <SEP> ㅇ ㅔ <SEP> <SPC> ㅂ ㅏ <S...,ㅇ ㅖ ㅅ <SEP> ㄴ ㅏ ㄹ <SEP> ㅇ ㅔ <SEP> <SPC> ㅂ ㅏ <S...,60대 이상,DGDQ20000020.json,8,train,95.0
2,ㄱ ㅜ <SEP> ㅅ ㅣ ㅂ <SEP> <SPC> ㅁ ㅕ ㅊ <SEP> <SPC> ...,ㄱ ㅜ <SEP> ㅅ ㅣ ㅂ <SEP> <SPC> ㅁ ㅕ ㅊ <SEP> <SPC> ...,60대 이상,DGDQ20000020.json,5,train,41.0
3,ㄱ ㅡ <SEP> ㄸ ㅐ <SEP> ㄱ ㅏ <SEP> <SPC> ㅇ ㅔ ㅁ <SEP...,ㄱ ㅡ <SEP> ㄸ ㅐ <SEP> ㄱ ㅏ <SEP> <SPC> ㅇ ㅔ ㅁ <SEP...,60대 이상,DGDQ20000020.json,9,train,87.0
4,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㅇ ㅔ ㅁ <SEP...,ㄱ ㅡ <SEP> ㄹ ㅐ <SEP> ㅅ ㅓ <SEP> <SPC> ㅇ ㅔ ㅁ <SEP...,60대 이상,DGDQ20000020.json,10,train,85.0
...,...,...,...,...,...,...,...
1024226,ㅇ ㅣ ㄴ <SEP> ㅈ ㅔ <SEP> <SPC> ㄱ ㅚ <SEP> ㄱ ㅣ <SEP...,ㅇ ㅣ ㄴ <SEP> ㅈ ㅔ <SEP> <SPC> ㄱ ㅗ <SEP> ㄱ ㅣ <SEP...,30대,DGIN21801133.json,10,test,100.0
1024227,ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> <SPC> ㅈ ㅣ ㄹ <SEP> ㅇ ㅣ <S...,ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> <SPC> ㅈ ㅣ ㄹ <SEP> ㅇ ㅣ <S...,30대,DGIN21801133.json,6,test,57.0
1024228,ㅇ ㅓ <SEP> ㄹ ㅕ ㅆ <SEP> ㅇ ㅡ ㄹ <SEP> <SPC> ㄸ ㅐ <S...,ㅇ ㅓ <SEP> ㄹ ㅕ ㅆ <SEP> ㅇ ㅡ ㄹ <SEP> <SPC> ㄸ ㅐ <S...,30대,DGIN21801133.json,13,test,142.0
1024229,ㅁ ㅓ ㄱ <SEP> ㅇ ㅓ ㅆ <SEP> ㅇ ㅓ ㅆ <SEP> ㄷ ㅓ ㄴ <SEP...,ㅁ ㅓ ㄱ <SEP> ㅇ ㅓ ㅆ <SEP> ㅇ ㅓ ㅆ <SEP> ㄷ ㅓ ㄴ <SEP...,30대,DGIN21801133.json,15,test,146.0
1024230,ㄴ ㅐ <SEP> ㄱ ㅏ <SEP> <SPC> ㅇ ㅣ ㄹ <SEP> ㅇ ㅡ ㄹ <S...,ㄴ ㅐ <SEP> ㄱ ㅏ <SEP> <SPC> ㅇ ㅣ ㄹ <SEP> ㅇ ㅡ ㄹ <S...,30대,DGIN21801133.json,11,test,111.0

In [16]:
gw_jamo["토큰 길이"].median()

68.0

In [40]:
print(max(gw_jamo["토큰 길이"].to_list()))
print(min(gw_jamo["토큰 길이"].to_list()))

535.0
19.0

구간은 10개. 구간 길이는 535-19=516

구간 한 개는 516 / 10 = 51

- 484-535
- 432-483
- 380-431
- 328-379
- 276-327
- 224-275
- 172-223
- 120-171
- 68-119
- 19-67

In [41]:
gw_jamo_1 = gw_jamo[(gw_jamo["토큰 길이"] >= 19) & (gw_jamo["토큰 길이"] < 68)]

gw_jamo_1.to_csv("/workspace/datas/gangwon/gangwon_dialect_jamo_integration_1.csv")

print(len(gw_jamo_1[gw_jamo_1["셋"] == "train"]))

427991

In [42]:
gw_jamo_2 = gw_jamo[(gw_jamo["토큰 길이"] >= 68) & (gw_jamo["토큰 길이"] < 120)]

gw_jamo_2.to_csv("/workspace/datas/gangwon/gangwon_dialect_jamo_integration_2.csv")

print(len(gw_jamo_2[gw_jamo_2["셋"] == "train"]))

366962

In [43]:
gw_jamo_3 = gw_jamo[(gw_jamo["토큰 길이"] >= 120) & (gw_jamo["토큰 길이"] < 172)]

gw_jamo_3.to_csv("/workspace/datas/gangwon/gangwon_dialect_jamo_integration_3.csv")

print(len(gw_jamo_3[gw_jamo_3["셋"] == "train"]))

42762

In [44]:
gw_jamo_4 = gw_jamo[(gw_jamo["토큰 길이"] >= 172) & (gw_jamo["토큰 길이"] < 224)]

gw_jamo_4.to_csv("/workspace/datas/gangwon/gangwon_dialect_jamo_integration_4.csv")

print(len(gw_jamo_4[gw_jamo_4["셋"] == "train"]))

3480

In [45]:
gw_jamo_5 = gw_jamo[(gw_jamo["토큰 길이"] >= 224) & (gw_jamo["토큰 길이"] < 276)]

gw_jamo_5.to_csv("/workspace/datas/gangwon/gangwon_dialect_jamo_integration_5.csv")

print(len(gw_jamo_5[gw_jamo_5["셋"] == "train"]))

277

In [46]:
gw_jamo_6 = gw_jamo[(gw_jamo["토큰 길이"] >= 276) & (gw_jamo["토큰 길이"] < 328)]

gw_jamo_6.to_csv("/workspace/datas/gangwon/gangwon_dialect_jamo_integration_6.csv")

print(len(gw_jamo_6[gw_jamo_6["셋"] == "train"]))

40

In [47]:
gw_jamo_7 = gw_jamo[(gw_jamo["토큰 길이"] >= 328) & (gw_jamo["토큰 길이"] < 380)]

gw_jamo_7.to_csv("/workspace/datas/gangwon/gangwon_dialect_jamo_integration_7.csv")

print(len(gw_jamo_7[gw_jamo_7["셋"] == "train"]))

14

In [50]:
gw_jamo_8 = gw_jamo[(gw_jamo["토큰 길이"] >= 380) & (gw_jamo["토큰 길이"] < 432)]

gw_jamo_8.to_csv("/workspace/datas/gangwon/gangwon_dialect_jamo_integration_8.csv")

print(len(gw_jamo_8[gw_jamo_8["셋"] == "train"]))

11

In [49]:
gw_jamo_9 = gw_jamo[(gw_jamo["토큰 길이"] >= 432) & (gw_jamo["토큰 길이"] < 484)]

gw_jamo_9.to_csv("/workspace/datas/gangwon/gangwon_dialect_jamo_integration_9.csv")

print(len(gw_jamo_9[gw_jamo_9["셋"] == "train"]))

0

In [51]:
gw_jamo_10 = gw_jamo[(gw_jamo["토큰 길이"] >= 484) & (gw_jamo["토큰 길이"] < 536)]

gw_jamo_10.to_csv("/workspace/datas/gangwon/gangwon_dialect_jamo_integration_10.csv")

print(len(gw_jamo_10[gw_jamo_10["셋"] == "train"]))

3

# 경상 방언

In [52]:
gs_jamo = pd.read_csv("/workspace/datas/gyeongsang/gyeongsang_dialect_jamo_integration.csv", index_col=0)

gs_jamo

,방언,표준어,연령대,출처 파일,길이,셋
0,ㅇ ㅏ <SEP> ~ <SEP> <SPC> ㅇ ㅣ <SEP> <SPC> ㄴ ㅗ <S...,ㅇ ㅏ <SEP> ~ <SEP> <SPC> ㅇ ㅣ <SEP> <SPC> ㄴ ㅗ <S...,20대,DKSR20002079.json,7,train
1,ㄸ ㅏ ㅇ <SEP> ㅇ ㅣ <SEP> ㄴ ㅏ <SEP> <SPC> ㅇ ㅣ <SEP...,ㄸ ㅏ ㅇ <SEP> ㅇ ㅣ <SEP> ㄴ ㅏ <SEP> <SPC> ㅇ ㅣ <SEP...,50대,DKCI20002541.json,8,train
2,ㅇ ㅓ <SEP> ㅉ ㅐ ㅆ <SEP> ㄱ ㅓ ㄴ <SEP> <SPC> ㅇ ㅏ <S...,ㅇ ㅓ <SEP> ㅉ ㅐ ㅆ <SEP> ㄱ ㅓ ㄴ <SEP> <SPC> ㅇ ㅏ <S...,50대,DKCI20003110.json,18,train
3,ㅅ ㅐ ㅇ <SEP> ㅎ ㅘ ㄹ <SEP> <SPC> ㅂ ㅗ <SEP> ㅁ ㅕ ㄴ ...,ㅅ ㅐ ㅇ <SEP> ㅎ ㅘ ㄹ <SEP> <SPC> ㅂ ㅗ <SEP> ㅁ ㅕ ㄴ ...,20대,DKSR20000643.json,6,train
4,ㄱ ㅡ <SEP> ㄴ ㅑ ㅇ <SEP> <SPC> ㅂ ㅏ <SEP> ㄹ ㅡ <SEP...,ㄱ ㅡ <SEP> ㄴ ㅑ ㅇ <SEP> <SPC> ㅂ ㅏ <SEP> ㄹ ㅡ <SEP...,10대,DKSR20003850.json,5,train
...,...,...,...,...,...,...
229489,ㅈ ㅔ <SEP> ㅇ ㅣ ㄹ <SEP> <SPC> ㅂ ㅕ ㄹ <SEP> ㄹ ㅗ <S...,ㅈ ㅔ <SEP> ㅇ ㅣ ㄹ <SEP> <SPC> ㅂ ㅕ ㄹ <SEP> ㄹ ㅗ <S...,20대,DKSR20001736.json,9,test
229490,ㅈ ㅔ <SEP> ㅇ ㅣ ㄹ <SEP> <SPC> ㅂ ㅕ ㄹ <SEP> ㄹ ㅗ <S...,ㅈ ㅔ <SEP> ㅇ ㅣ ㄹ <SEP> <SPC> ㅂ ㅕ ㄹ <SEP> ㄹ ㅗ <S...,20대,DKSR20001736.json,7,test
229491,ㄱ ㅡ <SEP> ~ <SEP> <SPC> ㅈ ㅏ <SEP> ㅈ ㅓ ㄴ <SEP> ...,ㄱ ㅡ <SEP> ~ <SEP> <SPC> ㅈ ㅏ <SEP> ㅈ ㅓ ㄴ <SEP> ...,20대,DKSR20001736.json,7,test
229493,ㄷ ㅟ <SEP> ㅇ ㅔ <SEP> <SPC> ㄴ ㅐ <SEP> ㄱ ㅏ <SEP> ...,ㄷ ㅟ <SEP> ㅇ ㅔ <SEP> <SPC> ㄴ ㅐ <SEP> ㄱ ㅏ <SEP> ...,20대,DKSR20001736.json,9,test
229496,ㄱ ㅡ <SEP> ㄱ ㅓ <SEP> <SPC> ㅌ ㅏ <SEP> ㄱ ㅏ <SEP> ...,ㄱ ㅡ <SEP> ㄱ ㅓ <SEP> <SPC> ㅌ ㅏ <SEP> ㄱ ㅏ <SEP> ...,20대,DKSR20001736.json,8,test

In [53]:
gs_jamo = gs_jamo.reset_index(drop=True)

seq_len_list = []
for sentence in gs_jamo["방언"].to_list():
    seq_len = len(sentence.split())
    
    seq_len_list.append(seq_len)

gs_jamo.loc[gs_jamo.index, "토큰 길이"] = seq_len_list

gs_jamo

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
0,ㅇ ㅏ <SEP> ~ <SEP> <SPC> ㅇ ㅣ <SEP> <SPC> ㄴ ㅗ <S...,ㅇ ㅏ <SEP> ~ <SEP> <SPC> ㅇ ㅣ <SEP> <SPC> ㄴ ㅗ <S...,20대,DKSR20002079.json,7,train,70.0
1,ㄸ ㅏ ㅇ <SEP> ㅇ ㅣ <SEP> ㄴ ㅏ <SEP> <SPC> ㅇ ㅣ <SEP...,ㄸ ㅏ ㅇ <SEP> ㅇ ㅣ <SEP> ㄴ ㅏ <SEP> <SPC> ㅇ ㅣ <SEP...,50대,DKCI20002541.json,8,train,69.0
2,ㅇ ㅓ <SEP> ㅉ ㅐ ㅆ <SEP> ㄱ ㅓ ㄴ <SEP> <SPC> ㅇ ㅏ <S...,ㅇ ㅓ <SEP> ㅉ ㅐ ㅆ <SEP> ㄱ ㅓ ㄴ <SEP> <SPC> ㅇ ㅏ <S...,50대,DKCI20003110.json,18,train,188.0
3,ㅅ ㅐ ㅇ <SEP> ㅎ ㅘ ㄹ <SEP> <SPC> ㅂ ㅗ <SEP> ㅁ ㅕ ㄴ ...,ㅅ ㅐ ㅇ <SEP> ㅎ ㅘ ㄹ <SEP> <SPC> ㅂ ㅗ <SEP> ㅁ ㅕ ㄴ ...,20대,DKSR20000643.json,6,train,54.0
4,ㄱ ㅡ <SEP> ㄴ ㅑ ㅇ <SEP> <SPC> ㅂ ㅏ <SEP> ㄹ ㅡ <SEP...,ㄱ ㅡ <SEP> ㄴ ㅑ ㅇ <SEP> <SPC> ㅂ ㅏ <SEP> ㄹ ㅡ <SEP...,10대,DKSR20003850.json,5,train,44.0
...,...,...,...,...,...,...,...
789808,ㅈ ㅔ <SEP> ㅇ ㅣ ㄹ <SEP> <SPC> ㅂ ㅕ ㄹ <SEP> ㄹ ㅗ <S...,ㅈ ㅔ <SEP> ㅇ ㅣ ㄹ <SEP> <SPC> ㅂ ㅕ ㄹ <SEP> ㄹ ㅗ <S...,20대,DKSR20001736.json,9,test,91.0
789809,ㅈ ㅔ <SEP> ㅇ ㅣ ㄹ <SEP> <SPC> ㅂ ㅕ ㄹ <SEP> ㄹ ㅗ <S...,ㅈ ㅔ <SEP> ㅇ ㅣ ㄹ <SEP> <SPC> ㅂ ㅕ ㄹ <SEP> ㄹ ㅗ <S...,20대,DKSR20001736.json,7,test,62.0
789810,ㄱ ㅡ <SEP> ~ <SEP> <SPC> ㅈ ㅏ <SEP> ㅈ ㅓ ㄴ <SEP> ...,ㄱ ㅡ <SEP> ~ <SEP> <SPC> ㅈ ㅏ <SEP> ㅈ ㅓ ㄴ <SEP> ...,20대,DKSR20001736.json,7,test,56.0
789811,ㄷ ㅟ <SEP> ㅇ ㅔ <SEP> <SPC> ㄴ ㅐ <SEP> ㄱ ㅏ <SEP> ...,ㄷ ㅟ <SEP> ㅇ ㅔ <SEP> <SPC> ㄴ ㅐ <SEP> ㄱ ㅏ <SEP> ...,20대,DKSR20001736.json,9,test,73.0
789812,ㄱ ㅡ <SEP> ㄱ ㅓ <SEP> <SPC> ㅌ ㅏ <SEP> ㄱ ㅏ <SEP> ...,ㄱ ㅡ <SEP> ㄱ ㅓ <SEP> <SPC> ㅌ ㅏ <SEP> ㄱ ㅏ <SEP> ...,20대,DKSR20001736.json,8,test,87.0

In [54]:
print(max(gs_jamo["토큰 길이"].to_list()))
print(min(gs_jamo["토큰 길이"].to_list()))

600.0
19.0

구간은 10개. 구간 길이는 600-19=581

구간 한 개는 581 / 10 = 58

- 542-600
- 483-541
- 424-482
- 365-423
- 306-364
- 247-305
- 188-246
- 129-187
- 70-128
- 19-69

In [55]:
gs_jamo_1 = gs_jamo[gs_jamo["토큰 길이"] <= 69]

gs_jamo_1.to_csv("/workspace/datas/gyeongsang/gyeongsang_dialect_jamo_integration_1.csv")

print(len(gs_jamo_1[gs_jamo_1["셋"] == "train"]))

187769

In [56]:
gs_jamo_2 = gs_jamo[(gs_jamo["토큰 길이"] >= 70) & (gs_jamo["토큰 길이"] < 129)]

gs_jamo_2.to_csv("/workspace/datas/gyeongsang/gyeongsang_dialect_jamo_integration_2.csv")

print(len(gs_jamo_2[gs_jamo_2["셋"] == "train"]))

336865

In [57]:
gs_jamo_3 = gs_jamo[(gs_jamo["토큰 길이"] >= 129) & (gs_jamo["토큰 길이"] < 188)]

gs_jamo_3.to_csv("/workspace/datas/gyeongsang/gyeongsang_dialect_jamo_integration_3.csv")

print(len(gs_jamo_3[gs_jamo_3["셋"] == "train"]))

77072

In [58]:
gs_jamo_4 = gs_jamo[(gs_jamo["토큰 길이"] >= 188) & (gs_jamo["토큰 길이"] < 247)]

gs_jamo_4.to_csv("/workspace/datas/gyeongsang/gyeongsang_dialect_jamo_integration_4.csv")

print(len(gs_jamo_4[gs_jamo_4["셋"] == "train"]))

8020

In [59]:
gs_jamo_5 = gs_jamo[(gs_jamo["토큰 길이"] >= 247) & (gs_jamo["토큰 길이"] < 306)]

gs_jamo_5.to_csv("/workspace/datas/gyeongsang/gyeongsang_dialect_jamo_integration_5.csv")

print(len(gs_jamo_5[gs_jamo_5["셋"] == "train"]))

876

In [60]:
gs_jamo_6 = gs_jamo[(gs_jamo["토큰 길이"] >= 306) & (gs_jamo["토큰 길이"] < 365)]

gs_jamo_6.to_csv("/workspace/datas/gyeongsang/gyeongsang_dialect_jamo_integration_6.csv")

print(len(gs_jamo_6[gs_jamo_6["셋"] == "train"]))

141

In [61]:
gs_jamo_7 = gs_jamo[(gs_jamo["토큰 길이"] >= 365) & (gs_jamo["토큰 길이"] < 424)]

gs_jamo_7.to_csv("/workspace/datas/gyeongsang/gyeongsang_dialect_jamo_integration_7.csv")

print(len(gs_jamo_7[gs_jamo_7["셋"] == "train"]))

38

In [62]:
gs_jamo_8 = gs_jamo[(gs_jamo["토큰 길이"] >= 424) & (gs_jamo["토큰 길이"] < 483)]

gs_jamo_8.to_csv("/workspace/datas/gyeongsang/gyeongsang_dialect_jamo_integration_8.csv")

print(len(gs_jamo_8[gs_jamo_8["셋"] == "train"]))

6

In [63]:
gs_jamo_9 = gs_jamo[(gs_jamo["토큰 길이"] >= 483) & (gs_jamo["토큰 길이"] < 542)]

gs_jamo_9.to_csv("/workspace/datas/gyeongsang/gyeongsang_dialect_jamo_integration_9.csv")

print(len(gs_jamo_9[gs_jamo_9["셋"] == "train"]))

1

In [64]:
gs_jamo_10 = gs_jamo[(gs_jamo["토큰 길이"] >= 542) & (gs_jamo["토큰 길이"] < 601)]

gs_jamo_10.to_csv("/workspace/datas/gyeongsang/gyeongsang_dialect_jamo_integration_10.csv")

print(len(gs_jamo_10[gs_jamo_10["셋"] == "train"]))

2

# 전라 방언

In [65]:
jl_jamo = pd.read_csv("/workspace/datas/jeonla/jeonla_dialect_jamo_integration.csv", index_col=0)

jl_jamo

,방언,표준어,연령대,출처 파일,길이,셋
0,ㅁ ㅏ ㄱ <SEP> ㅅ ㅏ ㅇ <SEP> <SPC> ㅇ ㅘ ㄴ <SEP> ㅈ ㅓ ...,ㅁ ㅏ ㄱ <SEP> ㅅ ㅏ ㅇ <SEP> <SPC> ㅇ ㅘ ㄴ <SEP> ㅈ ㅓ ...,20대,DJSX20002683.json,15,train
1,ㅈ ㅗ ㅎ <SEP> ㅇ ㅡ ㄴ <SEP> <SPC> ㅊ ㅜ <SEP> ㅇ ㅓ ㄱ ...,ㅈ ㅗ ㅎ <SEP> ㅇ ㅡ ㄴ <SEP> <SPC> ㅊ ㅜ <SEP> ㅇ ㅓ ㄱ ...,30대,DJDG20002125.json,8,train
2,ㅉ ㅗ ㅁ <SEP> <SPC> ㅂ ㅗ <SEP> ㅁ ㅕ ㄴ <SEP> <SPC> ...,ㅈ ㅗ <SEP> ㄱ ㅡ ㅁ <SEP> <SPC> ㅂ ㅗ <SEP> ㅁ ㅕ ㄴ <S...,30대,DJSX20004304.json,5,train
3,ㄱ ㅏ <SEP> ㅅ ㅣ <SEP> ㄴ ㅏ <SEP> ㄷ ㅡ ㄹ <SEP> <SPC...,ㄱ ㅖ <SEP> ㅈ ㅣ ㅂ <SEP> ㅇ ㅏ <SEP> ㅇ ㅣ <SEP> ㄷ ㅡ ...,20대,DJDG20001833.json,12,train
4,ㄱ ㅓ <SEP> ㄱ ㅣ <SEP> ㅅ ㅓ <SEP> <SPC> ㅇ ㅓ <SEP> ...,ㄱ ㅓ <SEP> ㄱ ㅣ <SEP> ㅅ ㅓ <SEP> <SPC> ㅇ ㅓ <SEP> ...,20대,DJDD20000034.json,12,train
...,...,...,...,...,...,...
275119,ㅇ ㅣ ㄹ <SEP> ㅂ ㅏ ㄴ <SEP> <SPC> ㅅ ㅏ <SEP> ㄹ ㅏ ㅁ ...,ㅇ ㅣ ㄹ <SEP> ㅂ ㅏ ㄴ <SEP> <SPC> ㅅ ㅏ <SEP> ㄹ ㅏ ㅁ ...,30대,DJSX20003150.json,12,test
275120,ㄷ ㅓ <SEP> <SPC> ㄴ ㅏ <SEP> ㅇ ㅏ <SEP> ㄱ ㅏ <SEP> ...,ㄷ ㅓ <SEP> <SPC> ㄴ ㅏ <SEP> ㅇ ㅏ <SEP> ㄱ ㅏ <SEP> ...,30대,DJSX20003150.json,8,test
275123,ㅇ ㅓ <SEP> <SPC> ㅌ ㅐ ㄱ <SEP> ㅅ ㅣ <SEP> ㄱ ㅏ <SEP...,ㅇ ㅓ <SEP> <SPC> ㅌ ㅐ ㄱ <SEP> ㅅ ㅣ <SEP> ㄱ ㅏ <SEP...,30대,DJSX20003150.json,5,test
275133,ㅇ ㅣ <SEP> <SPC> ㅊ ㅓ ㄴ <SEP> <SPC> ㅇ ㅣ <SEP> <S...,ㅇ ㅣ <SEP> <SPC> ㅊ ㅓ ㄴ <SEP> <SPC> ㅇ ㅣ <SEP> <S...,30대,DJSX20003150.json,12,test
275134,ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> <SPC> ㅂ ㅏ ㄹ <SEP> ㅍ ㅛ <S...,ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> <SPC> ㅂ ㅏ ㄹ <SEP> ㅍ ㅛ <S...,30대,DJSX20003150.json,6,test

In [66]:
jl_jamo = jl_jamo.reset_index(drop=True)

seq_len_list = []
for sentence in jl_jamo["방언"].to_list():
    seq_len = len(sentence.split())
    
    seq_len_list.append(seq_len)

jl_jamo.loc[jl_jamo.index, "토큰 길이"] = seq_len_list

jl_jamo

,방언,표준어,연령대,출처 파일,길이,셋,토큰 길이
0,ㅁ ㅏ ㄱ <SEP> ㅅ ㅏ ㅇ <SEP> <SPC> ㅇ ㅘ ㄴ <SEP> ㅈ ㅓ ...,ㅁ ㅏ ㄱ <SEP> ㅅ ㅏ ㅇ <SEP> <SPC> ㅇ ㅘ ㄴ <SEP> ㅈ ㅓ ...,20대,DJSX20002683.json,15,train,161.0
1,ㅈ ㅗ ㅎ <SEP> ㅇ ㅡ ㄴ <SEP> <SPC> ㅊ ㅜ <SEP> ㅇ ㅓ ㄱ ...,ㅈ ㅗ ㅎ <SEP> ㅇ ㅡ ㄴ <SEP> <SPC> ㅊ ㅜ <SEP> ㅇ ㅓ ㄱ ...,30대,DJDG20002125.json,8,train,92.0
2,ㅉ ㅗ ㅁ <SEP> <SPC> ㅂ ㅗ <SEP> ㅁ ㅕ ㄴ <SEP> <SPC> ...,ㅈ ㅗ <SEP> ㄱ ㅡ ㅁ <SEP> <SPC> ㅂ ㅗ <SEP> ㅁ ㅕ ㄴ <S...,30대,DJSX20004304.json,5,train,35.0
3,ㄱ ㅏ <SEP> ㅅ ㅣ <SEP> ㄴ ㅏ <SEP> ㄷ ㅡ ㄹ <SEP> <SPC...,ㄱ ㅖ <SEP> ㅈ ㅣ ㅂ <SEP> ㅇ ㅏ <SEP> ㅇ ㅣ <SEP> ㄷ ㅡ ...,20대,DJDG20001833.json,12,train,120.0
4,ㄱ ㅓ <SEP> ㄱ ㅣ <SEP> ㅅ ㅓ <SEP> <SPC> ㅇ ㅓ <SEP> ...,ㄱ ㅓ <SEP> ㄱ ㅣ <SEP> ㅅ ㅓ <SEP> <SPC> ㅇ ㅓ <SEP> ...,20대,DJDD20000034.json,12,train,99.0
...,...,...,...,...,...,...,...
729326,ㅇ ㅣ ㄹ <SEP> ㅂ ㅏ ㄴ <SEP> <SPC> ㅅ ㅏ <SEP> ㄹ ㅏ ㅁ ...,ㅇ ㅣ ㄹ <SEP> ㅂ ㅏ ㄴ <SEP> <SPC> ㅅ ㅏ <SEP> ㄹ ㅏ ㅁ ...,30대,DJSX20003150.json,12,test,124.0
729327,ㄷ ㅓ <SEP> <SPC> ㄴ ㅏ <SEP> ㅇ ㅏ <SEP> ㄱ ㅏ <SEP> ...,ㄷ ㅓ <SEP> <SPC> ㄴ ㅏ <SEP> ㅇ ㅏ <SEP> ㄱ ㅏ <SEP> ...,30대,DJSX20003150.json,8,test,76.0
729328,ㅇ ㅓ <SEP> <SPC> ㅌ ㅐ ㄱ <SEP> ㅅ ㅣ <SEP> ㄱ ㅏ <SEP...,ㅇ ㅓ <SEP> <SPC> ㅌ ㅐ ㄱ <SEP> ㅅ ㅣ <SEP> ㄱ ㅏ <SEP...,30대,DJSX20003150.json,5,test,37.0
729329,ㅇ ㅣ <SEP> <SPC> ㅊ ㅓ ㄴ <SEP> <SPC> ㅇ ㅣ <SEP> <S...,ㅇ ㅣ <SEP> <SPC> ㅊ ㅓ ㄴ <SEP> <SPC> ㅇ ㅣ <SEP> <S...,30대,DJSX20003150.json,12,test,61.0
729330,ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> <SPC> ㅂ ㅏ ㄹ <SEP> ㅍ ㅛ <S...,ㄱ ㅡ ㄴ <SEP> ㄷ ㅔ <SEP> <SPC> ㅂ ㅏ ㄹ <SEP> ㅍ ㅛ <S...,30대,DJSX20003150.json,6,test,49.0

In [67]:
print(max(jl_jamo["토큰 길이"].to_list()))
print(min(jl_jamo["토큰 길이"].to_list()))

362.0
19.0

구간은 10개. 구간 길이는 362-19=343

구간 한 개는 343 / 10 = 34

- 328-362
- 293-327
- 258-292
- 223-257
- 188-222
- 153-187
- 118-152
- 83-117
- 48-82
- 19-47

In [68]:
jl_jamo_1 = jl_jamo[jl_jamo["토큰 길이"] <= 47]

jl_jamo_1.to_csv("/workspace/datas/jeonla/jeonla_dialect_jamo_integration_1.csv")

print(len(jl_jamo_1[jl_jamo_1["셋"] == "train"]))

33974

In [69]:
jl_jamo_2 = jl_jamo[(jl_jamo["토큰 길이"] >= 48) & (jl_jamo["토큰 길이"] < 83)]

jl_jamo_2.to_csv("/workspace/datas/jeonla/jeonla_dialect_jamo_integration_2.csv")

print(len(jl_jamo_2[jl_jamo_2["셋"] == "train"]))

208107

In [70]:
jl_jamo_3 = jl_jamo[(jl_jamo["토큰 길이"] >= 83) & (jl_jamo["토큰 길이"] < 118)]

jl_jamo_3.to_csv("/workspace/datas/jeonla/jeonla_dialect_jamo_integration_3.csv")

print(len(jl_jamo_3[jl_jamo_3["셋"] == "train"]))

169804

In [71]:
jl_jamo_4 = jl_jamo[(jl_jamo["토큰 길이"] >= 118) & (jl_jamo["토큰 길이"] < 153)]

jl_jamo_4.to_csv("/workspace/datas/jeonla/jeonla_dialect_jamo_integration_4.csv")

print(len(jl_jamo_4[jl_jamo_4["셋"] == "train"]))

73500

In [72]:
jl_jamo_5 = jl_jamo[(jl_jamo["토큰 길이"] >= 153) & (jl_jamo["토큰 길이"] < 188)]

jl_jamo_5.to_csv("/workspace/datas/jeonla/jeonla_dialect_jamo_integration_5.csv")

print(len(jl_jamo_5[jl_jamo_5["셋"] == "train"]))

19139

In [73]:
jl_jamo_6 = jl_jamo[(jl_jamo["토큰 길이"] >= 188) & (jl_jamo["토큰 길이"] < 223)]

jl_jamo_6.to_csv("/workspace/datas/jeonla/jeonla_dialect_jamo_integration_6.csv")

print(len(jl_jamo_6[jl_jamo_6["셋"] == "train"]))

3076

In [74]:
jl_jamo_7 = jl_jamo[(jl_jamo["토큰 길이"] >= 223) & (jl_jamo["토큰 길이"] < 258)]

jl_jamo_7.to_csv("/workspace/datas/jeonla/jeonla_dialect_jamo_integration_7.csv")

print(len(jl_jamo_7[jl_jamo_7["셋"] == "train"]))

635

In [75]:
jl_jamo_8 = jl_jamo[(jl_jamo["토큰 길이"] >= 258) & (jl_jamo["토큰 길이"] < 293)]

jl_jamo_8.to_csv("/workspace/datas/jeonla/jeonla_dialect_jamo_integration_8.csv")

print(len(jl_jamo_8[jl_jamo_8["셋"] == "train"]))

147

In [76]:
jl_jamo_9 = jl_jamo[(jl_jamo["토큰 길이"] >= 293) & (jl_jamo["토큰 길이"] < 328)]

jl_jamo_9.to_csv("/workspace/datas/jeonla/jeonla_dialect_jamo_integration_9.csv")

print(len(jl_jamo_9[jl_jamo_9["셋"] == "train"]))

31

In [77]:
jl_jamo_10 = jl_jamo[(jl_jamo["토큰 길이"] >= 328) & (jl_jamo["토큰 길이"] < 363)]

jl_jamo_10.to_csv("/workspace/datas/jeonla/jeonla_dialect_jamo_integration_10.csv")

print(len(jl_jamo_10[jl_jamo_10["셋"] == "train"]))

1